
print("started running")
import torch
import torch.nn as nn
#import torch.optim as optim
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from lime import lime_tabular
#classification_report, classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from lime.lime_tabular import LimeTabularExplainer
#for prepping data set as it uses words for descriptions
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

import io
import joblib
from sklearn.ensemble import RandomForestClassifier

from sklearn.preprocessing import StandardScaler
import torch.optim.lr_scheduler as lr_scheduler
from imblearn.over_sampling import SMOTENC
from io import StringIO
from sklearn.metrics import accuracy_score
import os
import re
from sklearn.metrics import classification_report

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import ExtraTreesClassifier
import lightgbm as lgb
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest,chi2
import lightgbm as lgb
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import shap
pAth = os.path.dirname(os.path.abspath(__file__))

data=pd.read_csv(os.path.join(pAth,'antibioticAIinclusivee.csv'))

'''
multiSwaps = {
              #'ENTEROCOCCUS._GALLINARUM':['ENTEROCOCCUSGALLINARUM', 'ENTEROCOCCUSCASSELIFLAVUS'],
              #'ENTEROCOCCUS_RARE_SPECIES':['ENTEROCOCCUSSPECIES', 'ENTEROCOCCUSAVIUM', 'ENTEROCOCCUSRAFFINOSUS', 'ENTEROCOCCUSDURANS/HIRAE', 'ENTEROCOCCUSDURANS'],
              #'MYCOBACTERIUMAVIUM_COMPLEX(MAC)':['MYCOBACTERIUMAVIUMCOMPLEX'],
              #'MYCOBACTERIUM_RAPID_GROWING(RGM)':['MYCOBACTERIUMIMMUNOGENUM','MYCOBACTERIUMNEOAURUM', 'ZZZMYCOBACTERIUMMUCOGENICUM', 'MYCOBACTERIUMABSCESSUSGROUP','MYCOBACTERIUMABSCESSUS', 'MYCOBACTERIUMFORTUITUM', 'MYCOBACTERIUMCHELONAE', 'MYCOBACTERIUMSPECIES-RAPIDGROWER','MYCOBACTERIUMFORTUITUMSPECIESGROUP'],
              #'CITROBACTER_FREUNDII_COMPLEX':['CITROBACTERFREUNDIICOMPLEX', 'CITROBACTERFREUNDII', 'CITROBACTERYOUNGAE', 'CITROBACTERBRAAKII'],
              #'CITROBACTER_AMALONATICUS':['CITROBACTERAMALONATICUS','ZZZCITROBACTERAMALONATICUS','CITROBACTERAMALONATICUSCOMPLEX'],
              'PROVIDENCIA_SPECIES':['PROVIDENCIARETTGERI', 'PROVIDENCIASTUARTII', 'PROVIDENCIASPECIES'],
              'SAMONELLA_SPECIES':['SALMONELLATYPHI', 'SALMONELLASPECIES', 'SALMONELLAENTERICA'],
              'BACTEROIDES_FRAGILIS_SPECIES':['ZZZBACTEROIDESFRAGILISGROUP','BACTEROIDESFRAGILIS'],
              'BURKHOLDERIACEPACIA_SPECIES':['BURKHOLDERIACEPACIA', 'BURKHOLDERIACEPACIACOMPLEX', 'BURKHOLDERIACEPACIACOMPLEXGENOMOVARI', 'BURKHOLDERIACENOCEPACIA', 'BURKHOLDERIAVIETNAMIENSIS', 'BURKHOLDERIAGLADIOLI','BURKHOLDERIAMULTIVORANS'],
              #'NOCARDIA_SPECIES':['NOCARDIAFARCINICA', 'NOCARDIANOVA', 'NOCARDIASPECIES', 'NOCARDIACYRIACIGEORGICA', 'NOCARDIATRANSVALENSISCOMPLEX', 'NOCARDIATRANSVALENSIS', 'NOCARDIAASTEROIDES', 'NORCARDIAWALLACEI','NOCARDIANOVACOMPLEX'],
              #'SERRATIA_SPECIES':['SERRATIAMARCESCENS', 'SERRATIARUBIDAEA', 'SERRATIALIQUEFACIENS', 'SERRATIAODORIFERA', 'SERRATIASPECIES', 'SERRATIAPLYMUTHICA'],
              'ACINETOBACTER_SPECIES':['ACINETOBACTERSPECIES', 'ACINETOBACTERBAUMANNIICOMPLEX', 'ACINETOBACTERBAUMANNII', 'ACINETOBACTERLWOFFI', 'ACINETOBACTERHAEMOLYTICUS'],
              'SPHINGOBACTERIUM_SPECIES':['SPHINGOBACTERIUMMULTIVORUM', 'SPHINGOBACTERIUMSPIRITIVORUM'],
              'RALSTONIA_SPECIES':['RALSTONIAMANNITOLILYTICA', 'RALSTONIASPECIES'],
              #'AEROMONA_SPECIES':['AEROMONASCAVIAE', 'AEROMONASHYDROPHILAGROUP', 'ZZAEROMONASHYDROPHILACOMPLEX', 'AEROMONASVERONII', 'ZZAEROMONASCAVIAECOMPLEX', 'AEROMONASSPECIES','ZZAEROMONASVERONIICOMPLEX'],
              'CHRYSEOBACTERIUM_SPECIES':['CHRYSEOBACTERIUMINDOLOGENES', 'CHRYSEOBACTERIUMSPECIES'],
              'RAOULTELLA_SPECIES':['RAOULTELLA', 'RAOULTELLAORNITHINOLYTICA', 'RAOULTELLAPLANTICOLA'],
              'ELIZABETHKINGIA_SPECIES':['ELIZABETHKINGIASPECIES', 'ELIZABETHKINGIAMENINGOSEPTICA'],
              'SPHINGOMONAS_SPECIES':['SPHINGOMONASPAUCIMOBILIS/PARAPAUCIMOBILIS', 'SPHINGOMONAS'],
              'KLUYVERA_SPECIES':['KLUYVERACRYOCRESCENS', 'KLUYVERAASCORBATA', 'KLUYVERASPECIES'],
              #'STREPTOCOCCUS_GROUPA':['STREP.GRPDNOTENTEROCOCCI','STREPTOCOCCUSPYOGENES(GROUPA)','STREPTOCOCCUSPYOGENES{GROUPA}'],
              #'STREPTOCOCCUS_VIRIDANS/ALPHAHEMOLYTIC':['STREPTOCOCCUSORALIS','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC,NOTS.PNEUMO','STREPTOCOCCUSPNEUMONIAE','STREPTOCOCCUSSALIVARIUSGROUP','STREPTOCOCCUSSALIVARIUS','STREPTOCOCCUSMUTANS','STREPTOCOCCUSMUTANSGROUP','STREPTOCOCCUSGORDONII','STREPTOCOCCUSMITISGROUP','STREPTOCOCCUSCONSTELLATUS','STREPTOCOCCUSMITIS','STREPTOCOCCUSSANGUINIS','STREPTOCOCCUSSANGUIS','STREPTOCOCCUSANGINOSUSGROUP','STREPTOCOCCUSPARASANGUINIS','STREPTOCOCCUSINTERMEDIUS','VIRIDANSGROUPSTREPTOCOCCI', 'VIRIDANSGROUPSTREPTOCOCCINOTS.PNEUMONIAE', 'STREPTOCOCCUSANGINOSUS', 'STREPTOCOCCUSMITIS/STREPTOCOCCUSORALIS'],
              #'STREPTOCOCCUS_GROUPB':['STREPTOCOCCUSAGALACTIAE(GROUPB)','STREPTOCOCCUSAGALACTIAE{GROUPB}'],
              #'STREPTOCOCCUS_GROUPC':['BETASTREPTOCOCCUSGROUPC','STREPTOCOCCUSDYSGALACTIAE','STREPTOCOCCUSDYSGALACTIAESUBSP.EQUISIMILIS(GROUPC/GSTR]'],
              #'STREPTOCOCCUS_GROUPD':['STREPTOCOCCUSGALLOLYTICUS,SUBSP.GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.PASTEURIANUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.PASTEURIANUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.GALLOLYTICUS','STREPTOCOCCUSBOVISGP','STREPTOCOCCUSBOVISGP', 'STREPTOCOCCUSBOVIS','STREPTOCOCCUSBOVISGP.'],
              #'PSEUDOMONAS_SPECIES':['PSEUDOMONASFLUORESCENS','PSEUDOMONASFLUORESCENSGROUP','PSEUDOMONASPUTIDA','PSEUDOMONASPUTIDAGROUP','PSEUDOMONASSTUTZERI','PSEUDOMONASSTUTZERIGROUP','PSEUDOMONASMENDOCINA','PSEUDOMONASAERUGINOSA(NON-MUCOIDCF)','PSEUDOMONASAERUGINOSA','MUCOIDPSEUDOMONASAERUGINOSA'],
              #'PSEUDOMONAS_NOT_AERUGINOSA':['PSEUDOMONASSPECIES-NOTP.AERUGINOSA','PSEUDOMONASORYZIHABITANS'],
              'PROTEUS_VULGARIS':['ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP'],
             }

  
multiSwaps = {'CORYNEBACTERIUM_PATHOGENCY_MODERATE':['CORYNEBACTERIUMSTRIATUM', 'CORYNEBACTERIUMMACGINLEYI', 'CORYNEBACTERIUMJEIKEIUM', 'CORYNEBACTERIUMPSEUDODIPHTHERITICUM','CORYNEBACTERIUMUREALYTICUM'],
              'CORYNEBACTERIUM_PATHOGENCY_LOW':['CORYNEBACTERIUMPROPINQUUM', 'CORYNEBACTERIUMACCOLENS', 'CORYNEBACTERIUMAMYCOLATUM', 'DIPHTHEROIDS-CORYNEBACTERIUMSPECIES', 'CORYNEBAC.STRIATUM/AMYCOLATUM'],
              'KLEBSIELLA.PNEUMONIAE':['KLEBSIELLAOZAENAE', 'KLEBSIELLAPNEUMONIAESSP.OZAENAE', 'KLEBSIELLAAEROGENES', 'KLEBSIELLAOXYTOCA', 'KLEBSIELLAPNEUMONIAE', 'ZZZENTEROBACTERAEROGENES'],
              'ENTEROCOCCUS._GALLINARUM':['ENTEROCOCCUSGALLINARUM', 'ENTEROCOCCUSCASSELIFLAVUS'],
              'ENTEROCOCCUS_RARE_SPECIES':['ENTEROCOCCUSSPECIES', 'ENTEROCOCCUSAVIUM', 'ENTEROCOCCUSRAFFINOSUS', 'ENTEROCOCCUSDURANS/HIRAE', 'ENTEROCOCCUSDURANS'],
              'MYCOBACTERIUMAVIUM_COMPLEX(MAC)':['MYCOBACTERIUMAVIUMCOMPLEX','CHROMOGENICAFB,NOTM.TUBERCULOSIS'],
              'MYCOBACTERIUM_RAPID_GROWING(RGM)':['MYCOBACTERIUMIMMUNOGENUM','MYCOBACTERIUMNEOAURUM', 'ZZZMYCOBACTERIUMMUCOGENICUM', 'MYCOBACTERIUMABSCESSUSGROUP','MYCOBACTERIUMABSCESSUS', 'MYCOBACTERIUMFORTUITUM', 'MYCOBACTERIUMCHELONAE', 'MYCOBACTERIUMSPECIES-RAPIDGROWER','MYCOBACTERIUMFORTUITUMSPECIESGROUP'],
              'CITROBACTER_FREUNDII_COMPLEX':['CITROBACTERFREUNDIICOMPLEX', 'CITROBACTERFREUNDII', 'CITROBACTERYOUNGAE', 'CITROBACTERBRAAKII'],
              'CITROBACTER_AMALONATICUS':['CITROBACTERAMALONATICUS','ZZZCITROBACTERAMALONATICUS','CITROBACTERAMALONATICUSCOMPLEX'],
              'COAGNEGATIVE_STAPHYLOCOCCUS_SPECIES':['STAPHYLOCOCCUSLUGDUNENSIS', 'COAGNEGATIVESTAPHYLOCOCCUS', 'STAPHYLOCOCCUSEPIDERMIDIS', 'STAPHNEGNOTLUGDUNENSIS','STAPHYLOCOCCUSHAEMOLYTICUS','STAPHYLOCOCCUSSPECIES-COAGNEGATIVE,NOTSTAPHSAPROPHYTICUS'],
              'STAPHYLOCOCCUSAUREUS_SPECIES': ['STAPHAUREUS{MRSA}','STAPHAUREUS(COLONYVARIANT-SMALLCOLONYOROTHERMORPHOTYPE)','STAPHYLOCOCCUSAUREUS'],
              'PROVIDENCIA_SPECIES':['PROVIDENCIARETTGERI', 'PROVIDENCIASTUARTII', 'PROVIDENCIASPECIES'],
              'SAMONELLA_SPECIES':['SALMONELLATYPHI', 'SALMONELLASPECIES', 'SALMONELLAENTERICA'],
              'BACTEROIDES_FRAGILIS_SPECIES':['ZZZBACTEROIDESFRAGILISGROUP','BACTEROIDESFRAGILIS'],
              'BURKHOLDERIACEPACIA_SPECIES':['BURKHOLDERIACEPACIA', 'BURKHOLDERIACEPACIACOMPLEX', 'BURKHOLDERIACEPACIACOMPLEXGENOMOVARI', 'BURKHOLDERIACENOCEPACIA', 'BURKHOLDERIAVIETNAMIENSIS', 'BURKHOLDERIAGLADIOLI','BURKHOLDERIAMULTIVORANS'],
              'NOCARDIA_SPECIES':['NOCARDIAFARCINICA', 'NOCARDIANOVA', 'NOCARDIASPECIES', 'NOCARDIACYRIACIGEORGICA', 'NOCARDIATRANSVALENSISCOMPLEX', 'NOCARDIATRANSVALENSIS', 'NOCARDIAASTEROIDES', 'NORCARDIAWALLACEI','NOCARDIANOVACOMPLEX'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERTAYLORAE', 'ENTEROBACTERCANCEROGENUS', 'ENTEROBACTERASBURIAE', 'ENTEROBACTERSPECIES', 'ENTEROBACTERAMNIGENUS', 'ENTEROBACTERGERGOVIAE', 'ENTEROBACTERCLOACAE','ENTEROBACTERAMNIGENUS1'],
              'SERRATIA_SPECIES':['SERRATIAMARCESCENS', 'SERRATIARUBIDAEA', 'SERRATIALIQUEFACIENS', 'SERRATIAODORIFERA', 'SERRATIASPECIES', 'SERRATIAPLYMUTHICA'],
              'ACINETOBACTER_SPECIES':['ACINETOBACTERSPECIES', 'ACINETOBACTERBAUMANNIICOMPLEX', 'ACINETOBACTERBAUMANNII', 'ACINETOBACTERLWOFFI', 'ACINETOBACTERHAEMOLYTICUS'],
              'SPHINGOBACTERIUM_SPECIES':['SPHINGOBACTERIUMMULTIVORUM', 'SPHINGOBACTERIUMSPIRITIVORUM'],
              'RALSTONIA_SPECIES':['RALSTONIAMANNITOLILYTICA', 'RALSTONIASPECIES'],
              'AEROMONA_SPECIES':['AEROMONASCAVIAE', 'AEROMONASHYDROPHILAGROUP', 'ZZAEROMONASHYDROPHILACOMPLEX', 'AEROMONASVERONII', 'ZZAEROMONASCAVIAECOMPLEX', 'AEROMONASSPECIES','ZZAEROMONASVERONIICOMPLEX'],
              'CHRYSEOBACTERIUM_SPECIES':['CHRYSEOBACTERIUMINDOLOGENES', 'CHRYSEOBACTERIUMSPECIES'],
              'ACHROMOBACTER_SPECIES':['ACHROMOBACTERSPECIES', 'ACHROMOBACTERXYLOSOXIDANS'],
              'RAOULTELLA_SPECIES':['RAOULTELLA', 'RAOULTELLAORNITHINOLYTICA', 'RAOULTELLAPLANTICOLA'],
              'ELIZABETHKINGIA_SPECIES':['ELIZABETHKINGIASPECIES', 'ELIZABETHKINGIAMENINGOSEPTICA'],
              'SPHINGOMONAS_SPECIES':['SPHINGOMONASPAUCIMOBILIS/PARAPAUCIMOBILIS', 'SPHINGOMONAS'],
              'KLUYVERA_SPECIES':['KLUYVERACRYOCRESCENS', 'KLUYVERAASCORBATA', 'KLUYVERASPECIES'],
              'STREPTOCOCCUS_GROUPA':['STREP.GRPDNOTENTEROCOCCI','STREPTOCOCCUSPYOGENES(GROUPA)','STREPTOCOCCUSPYOGENES{GROUPA}', 'BETASTREPTOCOCCUSSPECIES'],
              'STREPTOCOCCUS_VIRIDANS/ALPHAHEMOLYTIC':['STREPTOCOCCUSORALIS','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC,NOTS.PNEUMO','STREPTOCOCCUSPNEUMONIAE','STREPTOCOCCUSSALIVARIUSGROUP','STREPTOCOCCUSSALIVARIUS','STREPTOCOCCUSMUTANS','STREPTOCOCCUSMUTANSGROUP','STREPTOCOCCUSGORDONII','STREPTOCOCCUSMITISGROUP','STREPTOCOCCUSCONSTELLATUS','STREPTOCOCCUSMITIS','STREPTOCOCCUSSANGUINIS','STREPTOCOCCUSSANGUIS','STREPTOCOCCUSANGINOSUSGROUP','STREPTOCOCCUSPARASANGUINIS','STREPTOCOCCUSINTERMEDIUS','VIRIDANSGROUPSTREPTOCOCCI', 'VIRIDANSGROUPSTREPTOCOCCINOTS.PNEUMONIAE', 'STREPTOCOCCUSANGINOSUS', 'STREPTOCOCCUSMITIS/STREPTOCOCCUSORALIS'],
              'STREPTOCOCCUS_GROUPB':['STREPTOCOCCUSAGALACTIAE(GROUPB)','STREPTOCOCCUSAGALACTIAE{GROUPB}'],
              'STREPTOCOCCUS_GROUPC':['BETASTREPTOCOCCUSGROUPC','STREPTOCOCCUSDYSGALACTIAE','STREPTOCOCCUSDYSGALACTIAESUBSP.EQUISIMILIS(GROUPC/GSTR]'],
              'STREPTOCOCCUS_GROUPD':['STREPTOCOCCUSGALLOLYTICUS,SUBSP.GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.PASTEURIANUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.PASTEURIANUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.GALLOLYTICUS','STREPTOCOCCUSBOVISGP','STREPTOCOCCUSBOVISGP', 'STREPTOCOCCUSBOVIS','STREPTOCOCCUSBOVISGP.'],
              'PSEUDOMONAS_SPECIES':['PSEUDOMONASFLUORESCENS','PSEUDOMONASFLUORESCENSGROUP','PSEUDOMONASPUTIDA','PSEUDOMONASPUTIDAGROUP','PSEUDOMONASSTUTZERI','PSEUDOMONASSTUTZERIGROUP','PSEUDOMONASMENDOCINA','PSEUDOMONASAERUGINOSA(NON-MUCOIDCF)','PSEUDOMONASAERUGINOSA','MUCOIDPSEUDOMONASAERUGINOSA'],
              'PSEUDOMONAS_NOT_AERUGINOSA':['NON-FERMENTINGGRAMNEGATIVERODS-NOTP.AERUGINOSA','PSEUDOMONASSPECIES-NOTP.AERUGINOSA','PSEUDOMONASORYZIHABITANS'],
              'CLOSTIDIUMN_SPECIES':['CLOSTRIDIUMCLOSTRIDIOFORME', 'CLOSTRIDIUMPARAPUTRIFICUM', 'ZZZCLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSORDELLII', 'CLOSTRIDIUMTERTIUM', 'CLOSTRIDIUMRAMOSUM', 'CLOSTRIDIUMSPECIES,NOTPERFRINGENS', 'CLOSTRIDIUMINNOCUUM', 'CLOSTRIDIUMSEPTICUM', 'CLOSTRIDIUMPERFRINGENS'],
              'PROTEUS_NOT_MIRABILIS':['ZZZPROTEUSPENNERI','ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERTAYLORAE','ENTEROBACTERCANCEROGENUS','ENTEROBACTERASBURIAE','ENTEROBACTERSPECIES','ENTEROBACTERCLOACAECOMPLEX','ENTEROBACTER_SPECIES','ENTEROBACTERAMNIGENUS1'],
              'FUSOBACTERIUM':['FUSOBACTERIUMNECROPHORUM', 'FUSOBACTERIUMSPECIES', 'FUSOBACTERIUMNUCLEATUM'],
              'LACTOBACILLUS':['LACTOBACILLUSRHAMNOSUS', 'LACTOBACILLUSSPECIES', 'LACTOBACILLUSCASEI'],
              'AEROCOCCUS':['AEROCOCCUSURINAE', 'AEROCOCCUSSANGUINICOLA','AEROCOCCUSSPECIES'],
              'MORAXELLA':['MORAXELLAOSLOENSIS','MORAXELLANON-LIQUEFACIENS','MORAXELLASPECIES'],
              'ALCALIGENES':['ALCALIGENESSPECIES','ALCALIGENESFAECALIS'],
              'ESCHERICHIA_NOT_COLI':['ESCHERICHIAFERGUSONII', 'ESCHERICHIAVULNERIS','ESCHERICHIAHERMANII'],
              'TSUKAMURELLA':['TSUKAMURELLASPECIES', 'TSUKAMURELLAPULMONIS'],
              'BACTEROIDES_SPECIES':['BACTEROIDESUREOLYTICUS', 'BACTEROIDESCACCAE', 'BACTEROIDESOVATUS', 'BACTEROIDESUNIFORMIS', 'BACTEROIDESVULGATUS', 'BACTEROIDESTHETAIOTAOMICRON', 'PARABACTEROIDESDISTASONIS', 'ZZZBACTEROIDESDISTASONIS', 'BACTEROIDESVULGATUS']}



data['organism']=data['organism'].replace(['PSEUDOMONAS_NOT_AERUGINOSA','PSEUDOMONASSPECIES-FLUORESCENS/PUTIDAGROUP','OCHROBACTRUMANTHROPI', 'OCHROBACTRUM','MYROIDESSPECIES','BACILLUSSPECIES','STAPHYLOCOCCUSSPECIES-NOTSTAPH.AUREUS','ESCHERICHIASPECIES','CORYNEBACTERIUMSPECIES','ARCANOBACTERIUMHAEMOLYTICUM','PAENIBACILLUSSPECIES','BACTEROIDESSPECIES','LECLERCIAADECARBOXYLATA','STAPHYLOCOCCUSSPECIES,COAGPENDING','STAPHYLOCOCCUSSPECIES','CORYNEBACTERIUMDIPTHERIAE','CORYNEBACTERIUMSPECIES,NOTC.UREALYTICUM','BORDETELLABRONCHISEPTICA','PSEUDOMONASSPECIES','BACTEROIDESSPECIESNOTFRAGILIS','ANAEROBICGRAMPOSITIVECOCCI','PASTEURELLAMULTOCIDA','GORDONIASPECIES','ACTINOMYCESSPECIES','DERMABACTERHOMINIS','STREP.GRPDNOTENTEROCOCCI','MICROCOCCUSSPECIES','CULTUREPOSITIVEGRAMPOSITIVECOCCI','DIPHTHEROIDS-CORYNEBACTERIUMSPECIES','GRAMNEGATIVERODS-NONFERM,UNIDENTIFIED','ACIDFASTBACILLI','ANAEROBICGRAMPOSITIVERODS','ENTERICGRAMNEGATIVERODS','CULTUREPOSITIVEGRAMNEGATIVECOCCI','GRAMPOSITIVERODS','GRAMNEGATIVERODS','NONSPORE-FORMINGANAEROBICGRAMPOSITIVERODS','LACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS-UNIDENTIFIED','NONLACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS','ACIDFASTBACILLIDETECTEDINLIQUIDMEDIUM','PARABACTEROIDESSPECIES','LISTERIASPECIES','LISTERIAMONOCYTOGENES','STREPTOCOCCUSSPECIES', 'KLEBSIELLASPECIES', 'PROTEUSSPECIES', 'ARCANOBACTERIUMHAEMOLYTICUM ', 'CRONOBACTERSAKAZAKII', 'CHRYSEOMONASLUTEOLA', 'LEUCONOSTOCSPECIES', 'BETASTREPTOCOCCUSGROUPG', 'PREVOTELLASPECIES', 'PEDIOCOCCUSSP.','ABIOTROPHIASPECIES(ORGRANULICATELLASPECIES)', 'CAMPYLOBACTERSPECIES', 'HAFNIA','RAHNELLA', 'ANAEROBICGRAMNEGATIVERODS', 'SHEWANELLAPUTREFACIENS', 'SCHISTOSOMAHAEMATOBIUMOVA', 'MYCOBACTERIUMSPECIES',' LECLERCIAADECARBOXYLATA', 'EGGERTHELLALENTA', 'YERSINIAENTEROCOLITICA','LACTOCOCCUSSPECIES', 'FLAVOBACTERIUMSPECIES', 'BREVUNDIMONAS', 'PEPTOSTREPTOCOCCUSSPECIES', 'BREVIBACTERIUMSPECIES', 'ZZZBACTEROIDESNOTB.FRAGILISGRP', 'VEILLONELLASPECIES', 'SHIGELLASPECIES', 'EUBACTERIUMLENTUM', 'COMAMONASACIDOVORANS', 'EWINGELLAAMERICANA', 'OLIGELLAURETHRALIS', 'ZZZPROPIONIBACTERIUMACNES', 'HAEMOPHILUSACTINOMYCETEMCOMITANS', 'MICROBACTERIUMSPECIES',],np.nan)
data = data.dropna()

data['organism'] = data['organism'].replace([r'\(CARBAPENEMRESISTANT\)','-VANCORESISTANT'],'',regex=True)

for replaceM in multiSwaps:
    data['organism'] = data['organism'].replace(multiSwaps[replaceM], replaceM)
data['organism']=data['organism'].replace(['AEROCOCCUS'],np.nan)

print(len(data['organism'].unique()))
print(data.shape)
for organism,count in data['organism'].value_counts().items():
    print("organism: "+organism+ " "+str(count) )
'''
#data['description'] = data.loc[:,'organism']
#positives
#data['description']=data['description'].replace(['NOCARDIA_SPECIES','COAGNEGATIVE_STAPHYLOCOCCUS_SPECIES','STAPHYLOCOCCUSAUREUS_SPECIES','ENTEROCOCCUS._GALLINARUM','ENTEROCOCCUS_RARE_SPECIES','MYCOBACTERIUMAVIUM_COMPLEX(MAC)','MYCOBACTERIUM_RAPID_GROWING(RGM)''CORYNEBACTERIUM_PATHOGENCY_MODERATE','CORYNEBACTERIUM_PATHOGENCY_LOW'],np.nan)
#negatives
#data['description']=data['description'].replace(['RAOULTELLA_SPECIES','ACHROMOBACTER_SPECIES','CHRYSEOBACTERIUM_SPECIES','AEROMONA_SPECIES','RALSTONIA_SPECIES','SPHINGOBACTERIUM_SPECIES','ACINETOBACTER_SPECIES','SERRATIA_SPECIES','ENTEROBACTER_SPECIES','BURKHOLDERIACEPACIA_SPECIES','BACTEROIDES_FRAGILIS_SPECIES','SAMONELLA_SPECIES','PROVIDENCIA_SPECIES','CITROBACTER_FREUNDII_COMPLEX','CITROBACTER_AMALONATICUS','KLEBSIELLA.PNEUMONIAE',],np.nan)

multiSwaps = {'CORYNEBACTERIUM':['CORYNEBACTERIUMSTRIATUM', 'CORYNEBACTERIUMMACGINLEYI', 'CORYNEBACTERIUMJEIKEIUM', 'CORYNEBACTERIUMPSEUDODIPHTHERITICUM','CORYNEBACTERIUMUREALYTICUM','CORYNEBACTERIUMPROPINQUUM', 'CORYNEBACTERIUMACCOLENS', 'CORYNEBACTERIUMAMYCOLATUM', 'DIPHTHEROIDS-CORYNEBACTERIUMSPECIES', 'CORYNEBAC.STRIATUM/AMYCOLATUM'],
              'KLEBSIELLA.PNEUMONIAE':['KLEBSIELLAOZAENAE', 'KLEBSIELLAPNEUMONIAESSP.OZAENAE', 'KLEBSIELLAAEROGENES', 'KLEBSIELLAOXYTOCA', 'KLEBSIELLAPNEUMONIAE', 'ZZZENTEROBACTERAEROGENES'],
              'ENTEROCOCCUS._GALLINARUM':['ENTEROCOCCUSGALLINARUM', 'ENTEROCOCCUSCASSELIFLAVUS'],
              'ENTEROCOCCUS_RARE_SPECIES':['ENTEROCOCCUSSPECIES', 'ENTEROCOCCUSAVIUM', 'ENTEROCOCCUSRAFFINOSUS', 'ENTEROCOCCUSDURANS/HIRAE', 'ENTEROCOCCUSDURANS'],
              'MYCOBACTERIUMAVIUM_COMPLEX(MAC)':['MYCOBACTERIUMAVIUMCOMPLEX','CHROMOGENICAFB,NOTM.TUBERCULOSIS'],
              'MYCOBACTERIUM_RAPID_GROWING(RGM)':['MYCOBACTERIUMIMMUNOGENUM','MYCOBACTERIUMNEOAURUM', 'ZZZMYCOBACTERIUMMUCOGENICUM', 'MYCOBACTERIUMABSCESSUSGROUP','MYCOBACTERIUMABSCESSUS', 'MYCOBACTERIUMFORTUITUM', 'MYCOBACTERIUMCHELONAE', 'MYCOBACTERIUMSPECIES-RAPIDGROWER','MYCOBACTERIUMFORTUITUMSPECIESGROUP'],
              'CITROBACTER':['CITROBACTERKOSERI','ZZZCITROBACTERFARMERI','CITROBACTER_FREUNDII_COMPLEX','CITROBACTER_AMALONATICUS','CITROBACTERSPECIES','CITROBACTERFREUNDIICOMPLEX', 'CITROBACTERFREUNDII', 'CITROBACTERYOUNGAE', 'CITROBACTERBRAAKII','CITROBACTERAMALONATICUS','ZZZCITROBACTERAMALONATICUS','CITROBACTERAMALONATICUSCOMPLEX'],
              'COAGNEGATIVE_STAPHYLOCOCCUS_SPECIES':['STAPHYLOCOCCUSLUGDUNENSIS', 'COAGNEGATIVESTAPHYLOCOCCUS', 'STAPHYLOCOCCUSEPIDERMIDIS', 'STAPHNEGNOTLUGDUNENSIS','STAPHYLOCOCCUSHAEMOLYTICUS','STAPHYLOCOCCUSSPECIES-COAGNEGATIVE,NOTSTAPHSAPROPHYTICUS'],
              'STAPHYLOCOCCUSAUREUS_SPECIES': ['STAPHAUREUS{MRSA}','STAPHAUREUS(COLONYVARIANT-SMALLCOLONYOROTHERMORPHOTYPE)','STAPHYLOCOCCUSAUREUS'],
              'PROVIDENCIA_SPECIES':['PROVIDENCIARETTGERI', 'PROVIDENCIASTUARTII', 'PROVIDENCIASPECIES'],
              'SAMONELLA_SPECIES':['SALMONELLATYPHI', 'SALMONELLASPECIES', 'SALMONELLAENTERICA'],
              'BACTEROIDES_FRAGILIS_SPECIES':['ZZZBACTEROIDESFRAGILISGROUP','BACTEROIDESFRAGILIS'],
              'BURKHOLDERIACEPACIA_SPECIES':['BURKHOLDERIACEPACIA', 'BURKHOLDERIACEPACIACOMPLEX', 'BURKHOLDERIACEPACIACOMPLEXGENOMOVARI', 'BURKHOLDERIACENOCEPACIA', 'BURKHOLDERIAVIETNAMIENSIS', 'BURKHOLDERIAGLADIOLI','BURKHOLDERIAMULTIVORANS'],
              'NOCARDIA_SPECIES':['NOCARDIAFARCINICA', 'NOCARDIANOVA', 'NOCARDIASPECIES', 'NOCARDIACYRIACIGEORGICA', 'NOCARDIATRANSVALENSISCOMPLEX', 'NOCARDIATRANSVALENSIS', 'NOCARDIAASTEROIDES', 'NORCARDIAWALLACEI','NOCARDIANOVACOMPLEX'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERGERGOVIAE','ENTEROBACTERCLOACAE','ENTEROBACTERTAYLORAE', 'ENTEROBACTERCANCEROGENUS', 'ENTEROBACTERASBURIAE', 'ENTEROBACTERSPECIES', 'ENTEROBACTERAMNIGENUS', 'ENTEROBACTERGERGOVIAE', 'ENTEROBACTERCLOACAE','ENTEROBACTERAMNIGENUS1'],
              'SERRATIA_SPECIES':['SERRATIAMARCESCENS', 'SERRATIARUBIDAEA', 'SERRATIALIQUEFACIENS', 'SERRATIAODORIFERA', 'SERRATIASPECIES', 'SERRATIAPLYMUTHICA'],
              'ACINETOBACTER_SPECIES':['ACINETOBACTERSPECIES', 'ACINETOBACTERBAUMANNIICOMPLEX', 'ACINETOBACTERBAUMANNII', 'ACINETOBACTERLWOFFI', 'ACINETOBACTERHAEMOLYTICUS'],
              'SPHINGO_SPECIES':['SPHINGOBACTERIUMMULTIVORUM', 'SPHINGOBACTERIUMSPIRITIVORUM','SPHINGOMONASPAUCIMOBILIS/PARAPAUCIMOBILIS', 'SPHINGOMONAS'],
              'RALSTONIA_SPECIES':['RALSTONIAMANNITOLILYTICA', 'RALSTONIASPECIES'],
              'AEROMONA_SPECIES':['AEROMONASCAVIAE', 'AEROMONASHYDROPHILAGROUP', 'ZZAEROMONASHYDROPHILACOMPLEX', 'AEROMONASVERONII', 'ZZAEROMONASCAVIAECOMPLEX', 'AEROMONASSPECIES','ZZAEROMONASVERONIICOMPLEX'],
              'CHRYSEOBACTERIUM_SPECIES':['CHRYSEOBACTERIUMINDOLOGENES', 'CHRYSEOBACTERIUMSPECIES'],
              'ACHROMOBACTER_SPECIES':['ACHROMOBACTERSPECIES', 'ACHROMOBACTERXYLOSOXIDANS'],
              'RAOULTELLA_SPECIES':['RAOULTELLA', 'RAOULTELLAORNITHINOLYTICA', 'RAOULTELLAPLANTICOLA'],
              'ELIZABETHKINGIA_SPECIES':['ELIZABETHKINGIASPECIES', 'ELIZABETHKINGIAMENINGOSEPTICA'],
              'KLUYVERA_SPECIES':['KLUYVERACRYOCRESCENS', 'KLUYVERAASCORBATA', 'KLUYVERASPECIES'],
              'STREPTOCOCCUS_GROUPA':['STREP.GRPDNOTENTEROCOCCI','STREPTOCOCCUSPYOGENES(GROUPA)','STREPTOCOCCUSPYOGENES{GROUPA}', 'BETASTREPTOCOCCUSSPECIES'],
              'STREPTOCOCCUS_VIRIDANS/ALPHAHEMOLYTIC':['STREPTOCOCCUSORALIS','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC,NOTS.PNEUMO','STREPTOCOCCUSPNEUMONIAE','STREPTOCOCCUSSALIVARIUSGROUP','STREPTOCOCCUSSALIVARIUS','STREPTOCOCCUSMUTANS','STREPTOCOCCUSMUTANSGROUP','STREPTOCOCCUSGORDONII','STREPTOCOCCUSMITISGROUP','STREPTOCOCCUSCONSTELLATUS','STREPTOCOCCUSMITIS','STREPTOCOCCUSSANGUINIS','STREPTOCOCCUSSANGUIS','STREPTOCOCCUSANGINOSUSGROUP','STREPTOCOCCUSPARASANGUINIS','STREPTOCOCCUSINTERMEDIUS','VIRIDANSGROUPSTREPTOCOCCI', 'VIRIDANSGROUPSTREPTOCOCCINOTS.PNEUMONIAE', 'STREPTOCOCCUSANGINOSUS', 'STREPTOCOCCUSMITIS/STREPTOCOCCUSORALIS'],
              'STREPTOCOCCUS_GROUPB':['STREPTOCOCCUSAGALACTIAE(GROUPB)','STREPTOCOCCUSAGALACTIAE{GROUPB}'],
              'STREPTOCOCCUS_GROUPC':['BETASTREPTOCOCCUSGROUPC','STREPTOCOCCUSDYSGALACTIAE','STREPTOCOCCUSDYSGALACTIAESUBSP.EQUISIMILIS(GROUPC/GSTR]'],
              'STREPTOCOCCUS_GROUPD':['ZZZSTREPTOCOCCUS GALLOLYTICUS SUBSP. GALLOLYTICUS','STREPTOCOCCUS GALLOLYTICUS, SUBSP. GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.PASTEURIANUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.PASTEURIANUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.GALLOLYTICUS','STREPTOCOCCUSBOVISGP','STREPTOCOCCUSBOVISGP', 'STREPTOCOCCUSBOVIS','STREPTOCOCCUSBOVISGP.'],
              'PSEUDOMONAS_SPECIES':['PSEUDOMONAS MENDOCINA','NON-FERMENTINGGRAMNEGATIVERODS-NOTP.AERUGINOSA','PSEUDOMONASSPECIES-NOTP.AERUGINOSA','PSEUDOMONASORYZIHABITANS','PSEUDOMONASFLUORESCENS','PSEUDOMONASFLUORESCENSGROUP','PSEUDOMONASPUTIDA','PSEUDOMONASPUTIDAGROUP','PSEUDOMONASSTUTZERI','PSEUDOMONASSTUTZERIGROUP','PSEUDOMONASMENDOCINA','PSEUDOMONASAERUGINOSA(NON-MUCOIDCF)','PSEUDOMONASAERUGINOSA','MUCOIDPSEUDOMONASAERUGINOSA'],
              'CLOSTIDIUMN_SPECIES':['CLOSTRIDIUMCLOSTRIDIOFORME', 'CLOSTRIDIUMPARAPUTRIFICUM', 'ZZZCLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSORDELLII', 'CLOSTRIDIUMTERTIUM', 'CLOSTRIDIUMRAMOSUM', 'CLOSTRIDIUMSPECIES,NOTPERFRINGENS', 'CLOSTRIDIUMINNOCUUM', 'CLOSTRIDIUMSEPTICUM', 'CLOSTRIDIUMPERFRINGENS'],
              'PROTEUS_NOT_MIRABILIS':['ZZZPROTEUSPENNERI','ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERGERGOVIAE','ENTEROBACTERCLOACAE','ENTEROBACTERTAYLORAE','ENTEROBACTERCANCEROGENUS','ENTEROBACTERASBURIAE','ENTEROBACTERSPECIES','ENTEROBACTERCLOACAECOMPLEX','ENTEROBACTER_SPECIES','ENTEROBACTERAMNIGENUS1'],
              'FUSOBACTERIUM':['FUSOBACTERIUMNECROPHORUM', 'FUSOBACTERIUMSPECIES', 'FUSOBACTERIUMNUCLEATUM'],
              'LACTOBACILLUS':['LACTOBACILLUSRHAMNOSUS', 'LACTOBACILLUSSPECIES', 'LACTOBACILLUSCASEI'],
              'AEROCOCCUS':['AEROCOCCUS SPECIES','AEROCOCCUSURINAE', 'AEROCOCCUSSANGUINICOLA','AEROCOCCUSSPECIES'],
              'ALCALIGENES':['ALCALIGENESSPECIES','ALCALIGENESFAECALIS'],
              'ESCHERICHIA_NOT_COLI':['ESCHERICHIAFERGUSONII', 'ESCHERICHIAVULNERIS','ESCHERICHIAHERMANII'],
              'TSUKAMURELLA':['TSUKAMURELLASPECIES', 'TSUKAMURELLAPULMONIS'],
              'PANTOEA':['PANTOEAAGGLOMERANS','PANTOEASPECIES'],
              'BACTEROIDES_NOTFRAGILIS':['BACTEROIDES OVATUS','ZZZBACTEROIDES NOT B. FRAGILIS GRP','BACTEROIDES UNIFORMIS','BACTEROIDES UREOLYTICUS ','BACTEROIDESUREOLYTICUS', 'BACTEROIDESCACCAE', 'BACTEROIDESOVATUS', 'BACTEROIDESUNIFORMIS', 'BACTEROIDESVULGATUS', 'BACTEROIDESTHETAIOTAOMICRON', 'PARABACTEROIDESDISTASONIS', 'ZZZBACTEROIDESDISTASONIS', 'BACTEROIDESVULGATUS'],
              'MORAXELLA':['MORAXELLAOSLOENSIS','MORAXELLANON-LIQUEFACIENS','MORAXELLASPECIES']
              }

#'PSEUDOMONAS_NOT_AERUGINOSA','PSEUDOMONASSPECIES-FLUORESCENS/PUTIDAGROUP', ADDED TO PSEUDOMONAS REMOVED FROM REMOVE
data=data.drop_duplicates()
print(data['age'].unique())

#data['agregatedComorbidtyIndex'] = data[['charlsonCondition_anymalignancy/lymphoma/leukemia','charlsonCondition_cerebrovascularDisease','charlsonCondition_chronicPulmonaryDisease','charlsonCondition_congestiveHeartFailure','charlsonCondition_diabetesnoChronicComplication','charlsonCondition_diabeteswEndOrganDamage','charlsonCondition_hematologicDisease','charlsonCondition_metastaticSolidTumour','charlsonCondition_mildLiverDisease','charlsonCondition_moderateoSevereLiverDisease','charlsonCondition_myocardialInfraction','charlsonCondition_peripheralVascularDisease','charlsonCondition_renalDisease','charlsonCondition_rheumaticDisease']]
cols = ['charlsonCondition_anymalignancy/lymphoma/leukemia','charlsonCondition_cerebrovascularDisease','charlsonCondition_chronicPulmonaryDisease','charlsonCondition_congestiveHeartFailure','charlsonCondition_diabetesnoChronicComplication','charlsonCondition_diabeteswEndOrganDamage','charlsonCondition_hematologicDisease','charlsonCondition_metastaticSolidTumour','charlsonCondition_mildLiverDisease','charlsonCondition_moderateoSevereLiverDisease','charlsonCondition_myocardialInfraction','charlsonCondition_peripheralVascularDisease','charlsonCondition_renalDisease','charlsonCondition_rheumaticDisease']

data['organism'] = data['organism'].str.replace(' ','')
data['organism']=data['organism'].replace(['PSEUDOMONAS_NOT_AERUGINOSA','PSEUDOMONASSPECIES-FLUORESCENS/PUTIDAGROUP','GRAM NEGATIVE RODS','ZZZPROPIONIBACTERIUM ACNES','PASTEURELLA MULTOCIDA','HAEMOPHILUS ACTINOMYCETEMCOMITANS','ANAEROBIC GRAM NEGATIVE RODS','PAENIBACILLUS SPECIES','OCHROBACTRUMANTHROPI', 'OCHROBACTRUM','MYROIDESSPECIES','BACILLUSSPECIES','STAPHYLOCOCCUSSPECIES-NOTSTAPH.AUREUS','ESCHERICHIASPECIES','CORYNEBACTERIUMSPECIES','ARCANOBACTERIUMHAEMOLYTICUM','PAENIBACILLUSSPECIES','BACTEROIDESSPECIES','LECLERCIAADECARBOXYLATA','STAPHYLOCOCCUSSPECIES,COAGPENDING','STAPHYLOCOCCUSSPECIES','CORYNEBACTERIUMDIPTHERIAE','CORYNEBACTERIUMSPECIES,NOTC.UREALYTICUM','BORDETELLABRONCHISEPTICA','PSEUDOMONASSPECIES','BACTEROIDESSPECIESNOTFRAGILIS','ANAEROBICGRAMPOSITIVECOCCI','PASTEURELLAMULTOCIDA','GORDONIASPECIES','ACTINOMYCESSPECIES','DERMABACTERHOMINIS','STREP.GRPDNOTENTEROCOCCI','MICROCOCCUSSPECIES','CULTUREPOSITIVEGRAMPOSITIVECOCCI','DIPHTHEROIDS-CORYNEBACTERIUMSPECIES','GRAMNEGATIVERODS-NONFERM,UNIDENTIFIED','ACIDFASTBACILLI','ANAEROBICGRAMPOSITIVERODS','ENTERICGRAMNEGATIVERODS','CULTUREPOSITIVEGRAMNEGATIVECOCCI','GRAMPOSITIVERODS','GRAMNEGATIVERODS','NONSPORE-FORMINGANAEROBICGRAMPOSITIVERODS','LACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS-UNIDENTIFIED','NONLACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS','ACIDFASTBACILLIDETECTEDINLIQUIDMEDIUM','PARABACTEROIDESSPECIES','LISTERIASPECIES','LISTERIAMONOCYTOGENES','STREPTOCOCCUSSPECIES', 'KLEBSIELLASPECIES', 'PROTEUSSPECIES', 'ARCANOBACTERIUMHAEMOLYTICUM ', 'CRONOBACTERSAKAZAKII', 'CHRYSEOMONASLUTEOLA', 'LEUCONOSTOCSPECIES', 'BETASTREPTOCOCCUSGROUPG', 'PREVOTELLASPECIES', 'PEDIOCOCCUSSP.','ABIOTROPHIASPECIES(ORGRANULICATELLASPECIES)', 'CAMPYLOBACTERSPECIES', 'HAFNIA','RAHNELLA', 'ANAEROBICGRAMNEGATIVERODS', 'SHEWANELLAPUTREFACIENS', 'SCHISTOSOMAHAEMATOBIUMOVA', 'MYCOBACTERIUMSPECIES',' LECLERCIAADECARBOXYLATA', 'EGGERTHELLALENTA', 'YERSINIAENTEROCOLITICA','LACTOCOCCUSSPECIES', 'FLAVOBACTERIUMSPECIES', 'BREVUNDIMONAS', 'PEPTOSTREPTOCOCCUSSPECIES', 'BREVIBACTERIUMSPECIES', 'ZZZBACTEROIDESNOTB.FRAGILISGRP', 'VEILLONELLASPECIES', 'SHIGELLASPECIES', 'EUBACTERIUMLENTUM', 'COMAMONASACIDOVORANS', 'EWINGELLAAMERICANA', 'OLIGELLAURETHRALIS', 'ZZZPROPIONIBACTERIUMACNES', 'HAEMOPHILUSACTINOMYCETEMCOMITANS', 'MICROBACTERIUMSPECIES'],np.nan)
data = data.dropna()

data['organism'] = data['organism'].replace([r'\(CARBAPENEMRESISTANT\)','-VANCORESISTANT'],'',regex=True)

multiSwapss = {'ENTEROBACTERIACEAE':['MORGANELLAMORGANII','ESCHERICHIA_NOT_COLI','SAMONELLA_SPECIES','HAFNIAALVEI','KLUYVERA_SPECIES'],
               'BURKHOLDERIACEPACIA':['SPHINGO_SPECIES','ACHROMOBACTER_SPECIES','BURKHOLDERIACEPACIA_SPECIES'],
               'STREPTOCOCCUS_NOT_VIRIDANS':['STREPTOCOCCUS_GROUPA','STREPTOCOCCUS_GROUPC','STREPTOCOCCUS_GROUPD'],
               'ENTEROCOCCUS':['ENTEROCOCCUS._GALLINARUM','ENTEROCOCCUS_RARE_SPECIES'],
               'PROTEUS':['PROTEUS_NOT_MIRABILIS','PROTEUSMIRABILIS']}
               #'CHRYSEOBACTERIUMsss]s_FAMILY':['CHRYSEOBACTERIUM_SPECIES','ELIZABETHKINGIA_SPECIES'],
              # 'STREPTOCOCCUS_NOT_GROUPB_/VIRIDANS':['STREPTOCOCCUS_GROUPA','STREPTOCOCCUS_GROUPC','STREPTOCOCCUS_GROUPD'],
               #,
               #'FUSOBACTERIA/BACTEROIDESFRAGILIS':['FUSOBACTERIUM','BACTEROIDES_FRAGILIS_SPECIES'],
              # 'PROTEUS':['PROTEUS_NOT_MIRABILIS','PROTEUSMIRABILIS'],
               #'NOCARDIA/TSUKAMURELLA':['TSUKAMURELLA','NOCARDIA_SPECIES'],
              # 'BURKHOLDERIA/SPHINGO_SPECIES':['SPHINGO_SPECIES','ACHROMOBACTER_SPECIES','BURKHOLDERIACEPACIA_SPECIES']}

for replaceM in multiSwaps:
    data['organism'] = data['organism'].replace(multiSwaps[replaceM], replaceM)

for replaceM in multiSwapss:
    data['organism'] = data['organism'].replace(multiSwapss[replaceM], replaceM)
data['organism']=data['organism'].replace(['MORAXELLA','AEROCOCCUS','LACTOBACILLUS','RHIZOBIUMRADIOBACTER'],np.nan)
data=data.dropna()

print(len(data['organism'].unique()))
print(data.shape)
for organism,count in data['organism'].value_counts().items():
    print("organism: "+organism+ " "+str(count) )

data=data.dropna()
ordTranslateAge = OrdinalEncoder(categories = [['18-24 years','25-34 years','35-44 years','45-54 years','55-64 years','65-74 years','75-84 years','85-89 years','above 90' ]])

print(data['antibiotic'].unique())

ordOrganism = OrdinalEncoder()

ordAntibiotic = OrdinalEncoder()


ordCultureDescription = OrdinalEncoder(categories=[['URINE','BLOOD','RESPIRATORY']])

tAge = ordTranslateAge.fit_transform(data[['age']])
tCulture = ordCultureDescription.fit_transform(data[['culture_description']])
tOrganism = ordOrganism.fit_transform(data[['organism']])
tAntibiotic = ordAntibiotic.fit_transform(data[['antibiotic']])

ageDf = pd.DataFrame(tAge,columns=['age'],index=data.index)
cultureDf = pd.DataFrame(tCulture,columns=['culture_description'],index=data.index)
organismDf = pd.DataFrame(tOrganism,columns=['organism'],index=data.index)
antibioticDf = pd.DataFrame(tAntibiotic,columns=['antibiotic'],index=data.index)


joblib.dump(ordTranslateAge,os.path.join(pAth,'age.pkl'))
joblib.dump(ordOrganism,os.path.join(pAth,'organism.pkl'))
joblib.dump(ordCultureDescription,os.path.join(pAth,'culture.pkl'))
joblib.dump(ordAntibiotic,os.path.join(pAth,'antibiotic.pkl'))

print('dumped')
fdss = pd.concat([data.drop(columns=['age','culture_description','organism','antibiotic','anon_id','pat_enc_csn_id_coded' ,'order_proc_id_coded','was_positive']),ageDf,cultureDf,organismDf,antibioticDf],axis=1)



replaceItems = ['Inconclusive','Null','Synergism']
for itemReplace in replaceItems:
    fdss['susceptibility'] = fdss['susceptibility'].replace(itemReplace,np.nan)

fdss = fdss.dropna()
yTarget = fdss['susceptibility']
print(yTarget.unique())
print(yTarget.shape)#needs () for unique
print(fdss.shape)#no () for shape
fdss = fdss.drop('susceptibility',axis=1)

print(fdss.columns)
xTrain, xTest,yTrain,yTest=train_test_split(fdss,yTarget,test_size=0.2,random_state=42)
'''


print('train test split created')



print("features selected")

'''
'''
cateGroups = ['culture_description','organism','antibiotic']
cateIndeses =[]
for indice in cateGroups:
    cateIndeses.append(fdss.columns.get_loc(indice))
overSampledTrain = SMOTENC(sampling_strategy={'Intermediate':141180,'Resistant':803164},random_state=42,categorical_features=cateIndeses,k_neighbors=5)
xtrainsmoted,ytrainsmoted = overSampledTrain.fit_resample(xTrain,yTrain)
'''
#xTrain = xTrain.to_numpy().astype(np.float32)
#print('oversampled')
print(xTrain.shape)

'''
print(xTest.shape)
antibioticAI = RandomForestClassifier(n_estimators=60,random_state=42)
print('model created')
antibioticAI.fit(xTrain,yTrain)
#antibioticAI = joblib.load('antibioticAIstage2.joblib')
'''
#antibioticAI = RandomForestClassifier(n_estimators=60,random_state=42)
antibioticAI = joblib.load('antibioticAIstage2.joblib')
print('model created')

#antibioticAI.fit(xTrain,yTrain)
print('model trained')
#joblib.dump(antibioticAI,filename='antibioticAIstage2.joblib')
'''
print('predictions made')
#yPred = antibioticAI.predict(xTest)
'''
'''
limeExplainer = LimeTabularExplainer(
    training_data=np.array(xTrain),
    feature_names = xTrain.columns,
    class_names=antibioticAI.classes_,
    mode='classification'
)
'''

limeExplainer = LimeTabularExplainer(
    training_data = np.array(xTrain),
    feature_names = list(xTrain.columns),
    class_names = antibioticAI.classes_,
    mode = "classification"
)
'''
'''
joblib.dump(limeExplainer,'limeExplainerStage2.joblib')
print('dumped')
sample = xTest.iloc[0].values
exp = limeExplainer.explain_instance(
    sample,
    antibioticAI.predict_proba,
    num_features = 10,
)
fig = exp.as_pyplot_figure()
plt.show()
#joblib.dump(limeExplainer,'limeExplainerStage2.joblib')

'''#print(classification_report(yTest,yPred))
#plt.show()
#plt.savefig('shapStage2.png')

fNames = fdss.columns.values
importance = antibioticAI.feature_importances_
fImportanceDF = pd.DataFrame({'Feature':fNames,'Gini Importance':importance}).sort_values('Gini Importance',ascending=False)


fImportanceDF.to_csv("Stage2AIfeatureImportanceCheck.csv")
#cm = confusion_matrix(yTest, yPred).astype(float)
#newCM = cm.copy()
#for i in range(len(cm)):
 #   summ = cm[i].sum()
  #  for j in range(len(cm[i])):
   #     percentage = round(cm[i][j] / summ,2)
    #    newCM[i][j] = percentage*100
#disp = ConfusionMatrixDisplay(confusion_matrix=newCM, display_labels=['Intermediate','Resistant','Susceptible'])
#disp.plot(cmap=plt.cm.Blues)
#plt.title('Confusion Matrix')
#plt.show()


print(fImportanceDF)
plt.figure(figsize=(8,4))
plt.barh(fNames, importance,color="blue")
plt.xlabel('Gini Importance')
plt.title('Feature Importance - Gini Importance')
plt.gca().invert_yaxis()
plt.show()

'''