print("started running")

#import torch.optim as optim
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#classification_report, classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

#for prepping data set as it uses words for descriptions
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import TargetEncoder
import io
import joblib
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import StandardScaler
import torch.optim.lr_scheduler as lr_scheduler

from io import StringIO
from sklearn.ensemble import RandomForestClassifier
#from sklearn.metrics import accuracy_score
import os
import re
from sklearn.metrics import classification_report
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.inspection import permutation_importance
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
pAth = os.path.dirname(os.path.abspath(__file__))
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import GroupShuffleSplit
import shap
data=pd.read_csv(os.path.join(pAth,'antibioticAIinclusivee.csv'))
print(len(data['organism'].unique()))
print(data.shape)
#swaps = {'ENTEROBACTERCLOACAECOMPLEX':'ENTEROBACTERCLOACAE','STREPTOCOCCUSAGALACTIAE{GROUPB}':'STREPTOCOCCUSAGALACTIAE(GROUPB)','STREPTOCOCCUSORALIS':'STREPTOCOCCUSMITIS/STREPTOCOCCUSORALIS','NOCARDIANOVACOMPLEX':'NOCARDIANOVA','ZZAEROMONASVERONIICOMPLEX':'AEROMONASVERONII','ZZZBACTEROIDESDISTASONIS':'PARABACTEROIDESDISTASONIS','MYCOBACTERIUMFORTUITUMSPECIESGROUP':'MYCOBACTERIUMFORTUITUM','BACTEROIDESSPECIESNOTFRAGILIS':'BACTEROIDESSPECIES','STREPTOCOCCUSDYSGALACTIAESUBSP.EQUISIMILIS(GROUPC/GSTR]':'STREPTOCOCCUSDYSGALACTIAE','CITROBACTERFREUNDIICOMPLEX':'CITROBACTERFREUNDII'}
#firstSwaps = {'PROTEUSVULGARIS':['ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP'],'CITROBACTERAMALONATICUS':['ZZZCITROBACTERAMALONATICUS','CITROBACTERAMALONATICUSCOMPLEX'],'STAPHYLOCOCCUSSPECIES':['STAPHYLOCOCCUSSPECIES-NOTSTAPH.AUREUS','STAPHYLOCOCCUSSPECIES-COAGNEGATIVE,NOTSTAPHSAPROPHYTICUS','STAPHYLOCOCCUSSPECIES,COAGPENDING','STAPHYLOCOCCUSHAEMOLYTICUS'],'BACTEROIDES':['ZZZBACTEROIDESFRAGILISGROUP','BACTEROIDESUREOLYTICUS','BACTEROIDESCACCAE','BACTEROIDESOVATUS'],'PSEUDOMONASPECIES':['PSEUDOMONASMENDOCINA','PSEUDOMONASPUTIDA','PSEUDOMONASFLUORESCENS','PSEUDOMONASSTUTZERI','PSEUDOMONASORYZIHABITANS','PSEUDOMONASSTUTZERIGROUP','PSEUDOMONASFLUORESCENSGROUP','PSEUDOMONASSPECIES-FLUORESCENS/PUTIDAGROUP','PSEUDOMONASSPECIES-NOTP.AERUGINOSA','PSEUDOMONASPUTIDAGROUP','PSEUDOMONASAERUGINOSA(NON-MUCOIDCF)','PSEUDOMONASAERUGINOSA'],
            #'FUSOBACTERIUM':['FUSOBACTERIUMNUCLEATUM','FUSOBACTERIUMSPECIES','FUSOBACTERIUMNECROPHORUM'],'STREPTOCOCCUSGROUPA':['STREPTOCOCCUSPYOGENES(GROUPA)','STREPTOCOCCUSPYOGENES{GROUPA}'],'STREPTOCOCCUSSVIRIDANS/ALPHA':['STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC,NOTS.PNEUMO','STREPTOCOCCUSPNEUMONIAE','STREPTOCOCCUSSALIVARIUSGROUP','STREPTOCOCCUSSALIVARIUS','STREPTOCOCCUSMUTANS','STREPTOCOCCUSMUTANSGROUP','STREPTOCOCCUSGORDONII','STREPTOCOCCUSMITISGROUP','STREPTOCOCCUSCONSTELLATUS','STREPTOCOCCUSMITIS','STREPTOCOCCUSSANGUINIS','STREPTOCOCCUSSANGUIS','STREPTOCOCCUSANGINOSUSGROUP','STREPTOCOCCUSPARASANGUINIS'],'STREPTOCOCCUSGROUPC':['BETASTREPTOCOCCUSGROUPC','STREPTOCOCCUSDYSGALACTIAE']
           # ,'STREPTOCOCCUSGROUPD':['STREPTOCOCCUSGALLOLYTICUS','SUBSP.GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.PASTEURIANUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.PASTEURIANUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.GALLOLYTICUS','STREPTOCOCCUSINTERMEDIUS','STREPTOCOCCUSBOVISGP']}
'''
multiSwaps = {
              'ENTEROCOCCUS._GALLINARUM':['ENTEROCOCCUSGALLINARUM', 'ENTEROCOCCUSCASSELIFLAVUS'],
              'ENTEROCOCCUS_RARE_SPECIES':['ENTEROCOCCUSSPECIES', 'ENTEROCOCCUSAVIUM', 'ENTEROCOCCUSRAFFINOSUS', 'ENTEROCOCCUSDURANS/HIRAE', 'ENTEROCOCCUSDURANS'],
              'MYCOBACTERIUMAVIUM_COMPLEX(MAC)':['MYCOBACTERIUMAVIUMCOMPLEX'],
              'MYCOBACTERIUM_RAPID_GROWING(RGM)':['MYCOBACTERIUMIMMUNOGENUM','MYCOBACTERIUMNEOAURUM', 'ZZZMYCOBACTERIUMMUCOGENICUM', 'MYCOBACTERIUMABSCESSUSGROUP','MYCOBACTERIUMABSCESSUS', 'MYCOBACTERIUMFORTUITUM', 'MYCOBACTERIUMCHELONAE', 'MYCOBACTERIUMSPECIES-RAPIDGROWER','MYCOBACTERIUMFORTUITUMSPECIESGROUP'],
              'CITROBACTER_FREUNDII_COMPLEX':['CITROBACTERFREUNDIICOMPLEX', 'CITROBACTERFREUNDII', 'CITROBACTERYOUNGAE', 'CITROBACTERBRAAKII'],
              'CITROBACTER_AMALONATICUS':['CITROBACTERAMALONATICUS','ZZZCITROBACTERAMALONATICUS','CITROBACTERAMALONATICUSCOMPLEX'],
              'PROVIDENCIA_SPECIES':['PROVIDENCIARETTGERI', 'PROVIDENCIASTUARTII', 'PROVIDENCIASPECIES'],
              'SAMONELLA_SPECIES':['SALMONELLATYPHI', 'SALMONELLASPECIES', 'SALMONELLAENTERICA'],
              'BACTEROIDES_FRAGILIS_SPECIES':['ZZZBACTEROIDESFRAGILISGROUP','BACTEROIDESFRAGILIS'],
              'BURKHOLDERIACEPACIA_SPECIES':['BURKHOLDERIACEPACIA', 'BURKHOLDERIACEPACIACOMPLEX', 'BURKHOLDERIACEPACIACOMPLEXGENOMOVARI', 'BURKHOLDERIACENOCEPACIA', 'BURKHOLDERIAVIETNAMIENSIS', 'BURKHOLDERIAGLADIOLI','BURKHOLDERIAMULTIVORANS'],
              'NOCARDIA_SPECIES':['NOCARDIAFARCINICA', 'NOCARDIANOVA', 'NOCARDIASPECIES', 'NOCARDIACYRIACIGEORGICA', 'NOCARDIATRANSVALENSISCOMPLEX', 'NOCARDIATRANSVALENSIS', 'NOCARDIAASTEROIDES', 'NORCARDIAWALLACEI','NOCARDIANOVACOMPLEX'],
              'SERRATIA_SPECIES':['SERRATIAMARCESCENS', 'SERRATIARUBIDAEA', 'SERRATIALIQUEFACIENS', 'SERRATIAODORIFERA', 'SERRATIASPECIES', 'SERRATIAPLYMUTHICA'],
              'ACINETOBACTER_SPECIES':['ACINETOBACTERSPECIES', 'ACINETOBACTERBAUMANNIICOMPLEX', 'ACINETOBACTERBAUMANNII', 'ACINETOBACTERLWOFFI', 'ACINETOBACTERHAEMOLYTICUS'],
              'SPHINGOBACTERIUM_SPECIES':['SPHINGOBACTERIUMMULTIVORUM', 'SPHINGOBACTERIUMSPIRITIVORUM'],
              'RALSTONIA_SPECIES':['RALSTONIAMANNITOLILYTICA', 'RALSTONIASPECIES'],
              'AEROMONA_SPECIES':['AEROMONASCAVIAE', 'AEROMONASHYDROPHILAGROUP', 'ZZAEROMONASHYDROPHILACOMPLEX', 'AEROMONASVERONII', 'ZZAEROMONASCAVIAECOMPLEX', 'AEROMONASSPECIES','ZZAEROMONASVERONIICOMPLEX'],
              'CHRYSEOBACTERIUM_SPECIES':['CHRYSEOBACTERIUMINDOLOGENES', 'CHRYSEOBACTERIUMSPECIES'],
              'RAOULTELLA_SPECIES':['RAOULTELLA', 'RAOULTELLAORNITHINOLYTICA', 'RAOULTELLAPLANTICOLA'],
              'ELIZABETHKINGIA_SPECIES':['ELIZABETHKINGIASPECIES', 'ELIZABETHKINGIAMENINGOSEPTICA'],
              'SPHINGOMONAS_SPECIES':['SPHINGOMONASPAUCIMOBILIS/PARAPAUCIMOBILIS', 'SPHINGOMONAS'],
              'KLUYVERA_SPECIES':['KLUYVERACRYOCRESCENS', 'KLUYVERAASCORBATA', 'KLUYVERASPECIES'],
              #'STREPTOCOCCUS_GROUPA':['STREP.GRPDNOTENTEROCOCCI','STREPTOCOCCUSPYOGENES(GROUPA)','STREPTOCOCCUSPYOGENES{GROUPA}'],
              #'STREPTOCOCCUS_VIRIDANS/ALPHAHEMOLYTIC':['STREPTOCOCCUSORALIS','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC,NOTS.PNEUMO','STREPTOCOCCUSPNEUMONIAE','STREPTOCOCCUSSALIVARIUSGROUP','STREPTOCOCCUSSALIVARIUS','STREPTOCOCCUSMUTANS','STREPTOCOCCUSMUTANSGROUP','STREPTOCOCCUSGORDONII','STREPTOCOCCUSMITISGROUP','STREPTOCOCCUSCONSTELLATUS','STREPTOCOCCUSMITIS','STREPTOCOCCUSSANGUINIS','STREPTOCOCCUSSANGUIS','STREPTOCOCCUSANGINOSUSGROUP','STREPTOCOCCUSPARASANGUINIS','STREPTOCOCCUSINTERMEDIUS','VIRIDANSGROUPSTREPTOCOCCI', 'VIRIDANSGROUPSTREPTOCOCCINOTS.PNEUMONIAE', 'STREPTOCOCCUSANGINOSUS', 'STREPTOCOCCUSMITIS/STREPTOCOCCUSORALIS'],
              #'STREPTOCOCCUS_GROUPB':['STREPTOCOCCUSAGALACTIAE(GROUPB)','STREPTOCOCCUSAGALACTIAE{GROUPB}'],
              #'STREPTOCOCCUS_GROUPC':['BETASTREPTOCOCCUSGROUPC','STREPTOCOCCUSDYSGALACTIAE','STREPTOCOCCUSDYSGALACTIAESUBSP.EQUISIMILIS(GROUPC/GSTR]'],
              'STREPTOCOCCUS_GROUPD':['STREPTOCOCCUSGALLOLYTICUS,SUBSP.GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.PASTEURIANUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.PASTEURIANUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.GALLOLYTICUS','STREPTOCOCCUSBOVISGP','STREPTOCOCCUSBOVISGP', 'STREPTOCOCCUSBOVIS','STREPTOCOCCUSBOVISGP.'],
              'PSEUDOMONAS_SPECIES':['PSEUDOMONASFLUORESCENS','PSEUDOMONASFLUORESCENSGROUP','PSEUDOMONASPUTIDA','PSEUDOMONASPUTIDAGROUP','PSEUDOMONASSTUTZERI','PSEUDOMONASSTUTZERIGROUP','PSEUDOMONASMENDOCINA','PSEUDOMONASAERUGINOSA(NON-MUCOIDCF)','PSEUDOMONASAERUGINOSA','MUCOIDPSEUDOMONASAERUGINOSA'],
              'PSEUDOMONAS_NOT_AERUGINOSA':['PSEUDOMONASSPECIES-NOTP.AERUGINOSA','PSEUDOMONASORYZIHABITANS'],
              'PROTEUS_VULGARIS':['ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP'],
             }

multiSwaps = {'CORYNEBACTERIUM_PATHOGENCY_MODERATE':['CORYNEBACTERIUMSTRIATUM', 'CORYNEBACTERIUMMACGINLEYI', 'CORYNEBACTERIUMJEIKEIUM', 'CORYNEBACTERIUMPSEUDODIPHTHERITICUM','CORYNEBACTERIUMUREALYTICUM'],
              'CORYNEBACTERIUM_PATHOGENCY_LOW':['CORYNEBACTERIUMPROPINQUUM', 'CORYNEBACTERIUMACCOLENS', 'CORYNEBACTERIUMAMYCOLATUM', 'DIPHTHEROIDS-CORYNEBACTERIUMSPECIES', 'CORYNEBAC.STRIATUM/AMYCOLATUM'],
              'KLEBSIELLA.PNEUMONIAE':['KLEBSIELLAOZAENAE', 'KLEBSIELLAPNEUMONIAESSP.OZAENAE', 'KLEBSIELLAAEROGENES', 'KLEBSIELLAOXYTOCA', 'KLEBSIELLAPNEUMONIAE', 'ZZZENTEROBACTERAEROGENES'],
              'ENTEROCOCCUS._GALLINARUM':['ENTEROCOCCUSGALLINARUM', 'ENTEROCOCCUSCASSELIFLAVUS'],
              'ENTEROCOCCUS_RARE_SPECIES':['ENTEROCOCCUSSPECIES', 'ENTEROCOCCUSAVIUM', 'ENTEROCOCCUSRAFFINOSUS', 'ENTEROCOCCUSDURANS/HIRAE', 'ENTEROCOCCUSDURANS'],
              'MYCOBACTERIUMAVIUM_COMPLEX(MAC)':['MYCOBACTERIUMAVIUMCOMPLEX'],
              'MYCOBACTERIUM_RAPID_GROWING(RGM)':['MYCOBACTERIUMIMMUNOGENUM','MYCOBACTERIUMNEOAURUM', 'ZZZMYCOBACTERIUMMUCOGENICUM', 'MYCOBACTERIUMABSCESSUSGROUP','MYCOBACTERIUMABSCESSUS', 'MYCOBACTERIUMFORTUITUM', 'MYCOBACTERIUMCHELONAE', 'MYCOBACTERIUMSPECIES-RAPIDGROWER','MYCOBACTERIUMFORTUITUMSPECIESGROUP'],
              'CITROBACTER_FREUNDII_COMPLEX':['CITROBACTERFREUNDIICOMPLEX', 'CITROBACTERFREUNDII', 'CITROBACTERYOUNGAE', 'CITROBACTERBRAAKII'],
              'CITROBACTER_AMALONATICUS':['CITROBACTERAMALONATICUS','ZZZCITROBACTERAMALONATICUS','CITROBACTERAMALONATICUSCOMPLEX'],
              'COAGNEGATIVE_STAPHYLOCOCCUS_SPECIES':['STAPHYLOCOCCUSLUGDUNENSIS', 'COAGNEGATIVESTAPHYLOCOCCUS', 'STAPHYLOCOCCUSEPIDERMIDIS', 'STAPHNEGNOTLUGDUNENSIS','STAPHYLOCOCCUSHAEMOLYTICUS','STAPHYLOCOCCUSSPECIES-COAGNEGATIVE,NOTSTAPHSAPROPHYTICUS'],
              'STAPHYLOCOCCUSAUREUS_SPECIES': ['STAPHAUREUS{MRSA}','STAPHAUREUS(COLONYVARIANT-SMALLCOLONYOROTHERMORPHOTYPE)','STAPHYLOCOCCUSAUREUS'],
              'PROVIDENCIA_SPECIES':['PROVIDENCIARETTGERI', 'PROVIDENCIASTUARTII', 'PROVIDENCIASPECIES'],
              'SAMONELLA_SPECIES':['SALMONELLATYPHI', 'SALMONELLASPECIES', 'SALMONELLAENTERICA'],
              'BACTEROIDES_FRAGILIS_SPECIES':['ZZZBACTEROIDESFRAGILISGROUP','BACTEROIDESFRAGILIS'],
              'BURKHOLDERIACEPACIA_SPECIES':['BURKHOLDERIACEPACIA', 'BURKHOLDERIACEPACIACOMPLEX', 'BURKHOLDERIACEPACIACOMPLEXGENOMOVARI', 'BURKHOLDERIACENOCEPACIA', 'BURKHOLDERIAVIETNAMIENSIS', 'BURKHOLDERIAGLADIOLI','BURKHOLDERIAMULTIVORANS'],
              'NOCARDIA_SPECIES':['NOCARDIAFARCINICA', 'NOCARDIANOVA', 'NOCARDIASPECIES', 'NOCARDIACYRIACIGEORGICA', 'NOCARDIATRANSVALENSISCOMPLEX', 'NOCARDIATRANSVALENSIS', 'NOCARDIAASTEROIDES', 'NORCARDIAWALLACEI','NOCARDIANOVACOMPLEX'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERTAYLORAE', 'ENTEROBACTERCANCEROGENUS', 'ENTEROBACTERASBURIAE', 'ENTEROBACTERSPECIES', 'ENTEROBACTERAMNIGENUS', 'ENTEROBACTERGERGOVIAE', 'ENTEROBACTERCLOACAE','ENTEROBACTERAMNIGENUS1'],
              'SERRATIA_SPECIES':['SERRATIAMARCESCENS', 'SERRATIARUBIDAEA', 'SERRATIALIQUEFACIENS', 'SERRATIAODORIFERA', 'SERRATIASPECIES', 'SERRATIAPLYMUTHICA'],
              'ACINETOBACTER_SPECIES':['ACINETOBACTERSPECIES', 'ACINETOBACTERBAUMANNIICOMPLEX', 'ACINETOBACTERBAUMANNII', 'ACINETOBACTERLWOFFI', 'ACINETOBACTERHAEMOLYTICUS'],
              'SPHINGOBACTERIUM_SPECIES':['SPHINGOBACTERIUMMULTIVORUM', 'SPHINGOBACTERIUMSPIRITIVORUM'],
              'RALSTONIA_SPECIES':['RALSTONIAMANNITOLILYTICA', 'RALSTONIASPECIES'],
              'AEROMONA_SPECIES':['AEROMONASCAVIAE', 'AEROMONASHYDROPHILAGROUP', 'ZZAEROMONASHYDROPHILACOMPLEX', 'AEROMONASVERONII', 'ZZAEROMONASCAVIAECOMPLEX', 'AEROMONASSPECIES','ZZAEROMONASVERONIICOMPLEX'],
              'CHRYSEOBACTERIUM_SPECIES':['CHRYSEOBACTERIUMINDOLOGENES', 'CHRYSEOBACTERIUMSPECIES'],
              'ACHROMOBACTER_SPECIES':['ACHROMOBACTERSPECIES', 'ACHROMOBACTERXYLOSOXIDANS'],
              'RAOULTELLA_SPECIES':['RAOULTELLA', 'RAOULTELLAORNITHINOLYTICA', 'RAOULTELLAPLANTICOLA'],
              'ELIZABETHKINGIA_SPECIES':['ELIZABETHKINGIASPECIES', 'ELIZABETHKINGIAMENINGOSEPTICA'],
              'SPHINGOMONAS_SPECIES':['SPHINGOMONASPAUCIMOBILIS/PARAPAUCIMOBILIS', 'SPHINGOMONAS'],
              'KLUYVERA_SPECIES':['KLUYVERACRYOCRESCENS', 'KLUYVERAASCORBATA', 'KLUYVERASPECIES'],
              'STREPTOCOCCUS_GROUPA':['STREP.GRPDNOTENTEROCOCCI','STREPTOCOCCUSPYOGENES(GROUPA)','STREPTOCOCCUSPYOGENES{GROUPA}'],
              'STREPTOCOCCUS_VIRIDANS/ALPHAHEMOLYTIC':['STREPTOCOCCUSORALIS','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC,NOTS.PNEUMO','STREPTOCOCCUSPNEUMONIAE','STREPTOCOCCUSSALIVARIUSGROUP','STREPTOCOCCUSSALIVARIUS','STREPTOCOCCUSMUTANS','STREPTOCOCCUSMUTANSGROUP','STREPTOCOCCUSGORDONII','STREPTOCOCCUSMITISGROUP','STREPTOCOCCUSCONSTELLATUS','STREPTOCOCCUSMITIS','STREPTOCOCCUSSANGUINIS','STREPTOCOCCUSSANGUIS','STREPTOCOCCUSANGINOSUSGROUP','STREPTOCOCCUSPARASANGUINIS','STREPTOCOCCUSINTERMEDIUS','VIRIDANSGROUPSTREPTOCOCCI', 'VIRIDANSGROUPSTREPTOCOCCINOTS.PNEUMONIAE', 'STREPTOCOCCUSANGINOSUS', 'STREPTOCOCCUSMITIS/STREPTOCOCCUSORALIS'],
              'STREPTOCOCCUS_GROUPB':['STREPTOCOCCUSAGALACTIAE(GROUPB)','STREPTOCOCCUSAGALACTIAE{GROUPB}'],
              'STREPTOCOCCUS_GROUPC':['BETASTREPTOCOCCUSGROUPC','STREPTOCOCCUSDYSGALACTIAE','STREPTOCOCCUSDYSGALACTIAESUBSP.EQUISIMILIS(GROUPC/GSTR]'],
              'STREPTOCOCCUS_GROUPD':['STREPTOCOCCUSGALLOLYTICUS,SUBSP.GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.PASTEURIANUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.PASTEURIANUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.GALLOLYTICUS','STREPTOCOCCUSBOVISGP','STREPTOCOCCUSBOVISGP', 'STREPTOCOCCUSBOVIS','STREPTOCOCCUSBOVISGP.'],
              'PSEUDOMONAS_SPECIES':['PSEUDOMONASFLUORESCENS','PSEUDOMONASFLUORESCENSGROUP','PSEUDOMONASPUTIDA','PSEUDOMONASPUTIDAGROUP','PSEUDOMONASSTUTZERI','PSEUDOMONASSTUTZERIGROUP','PSEUDOMONASMENDOCINA','PSEUDOMONASAERUGINOSA(NON-MUCOIDCF)','PSEUDOMONASAERUGINOSA','MUCOIDPSEUDOMONASAERUGINOSA'],
              'PSEUDOMONAS_NOT_AERUGINOSA':['PSEUDOMONASSPECIES-NOTP.AERUGINOSA','PSEUDOMONASORYZIHABITANS'],
              'CLOSTIDIUMN_SPECIES':['CLOSTRIDIUMCLOSTRIDIOFORME', 'CLOSTRIDIUMPARAPUTRIFICUM', 'ZZZCLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSORDELLII', 'CLOSTRIDIUMTERTIUM', 'CLOSTRIDIUMRAMOSUM', 'CLOSTRIDIUMSPECIES,NOTPERFRINGENS', 'CLOSTRIDIUMINNOCUUM', 'CLOSTRIDIUMSEPTICUM', 'CLOSTRIDIUMPERFRINGENS'],
              'PROTEUS_NOT_MIRABILIS':['ZZZPROTEUSPENNERI','ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERTAYLORAE','ENTEROBACTERCANCEROGENUS','ENTEROBACTERASBURIAE','ENTEROBACTERSPECIES','ENTEROBACTERCLOACAECOMPLEX','ENTEROBACTER_SPECIES','ENTEROBACTERAMNIGENUS1']}


multiSwaps = {'CORYNEBACTERIUM_PATHOGENCY_MODERATE':['CORYNEBACTERIUMSTRIATUM', 'CORYNEBACTERIUMMACGINLEYI', 'CORYNEBACTERIUMJEIKEIUM', 'CORYNEBACTERIUMPSEUDODIPHTHERITICUM','CORYNEBACTERIUMUREALYTICUM'],
              'CORYNEBACTERIUM_PATHOGENCY_LOW':['CORYNEBACTERIUMPROPINQUUM', 'CORYNEBACTERIUMACCOLENS', 'CORYNEBACTERIUMAMYCOLATUM', 'DIPHTHEROIDS-CORYNEBACTERIUMSPECIES', 'CORYNEBAC.STRIATUM/AMYCOLATUM'],
              'KLEBSIELLA.PNEUMONIAE':['KLEBSIELLAOZAENAE', 'KLEBSIELLAPNEUMONIAESSP.OZAENAE', 'KLEBSIELLAAEROGENES', 'KLEBSIELLAOXYTOCA', 'KLEBSIELLAPNEUMONIAE', 'ZZZENTEROBACTERAEROGENES'],
              'ENTEROCOCCUS._GALLINARUM':['ENTEROCOCCUSGALLINARUM', 'ENTEROCOCCUSCASSELIFLAVUS'],
              'ENTEROCOCCUS_RARE_SPECIES':['ENTEROCOCCUSSPECIES', 'ENTEROCOCCUSAVIUM', 'ENTEROCOCCUSRAFFINOSUS', 'ENTEROCOCCUSDURANS/HIRAE', 'ENTEROCOCCUSDURANS'],
              'MYCOBACTERIUMAVIUM_COMPLEX(MAC)':['MYCOBACTERIUMAVIUMCOMPLEX','CHROMOGENICAFB,NOTM.TUBERCULOSIS'],
              'MYCOBACTERIUM_RAPID_GROWING(RGM)':['MYCOBACTERIUMIMMUNOGENUM','MYCOBACTERIUMNEOAURUM', 'ZZZMYCOBACTERIUMMUCOGENICUM', 'MYCOBACTERIUMABSCESSUSGROUP','MYCOBACTERIUMABSCESSUS', 'MYCOBACTERIUMFORTUITUM', 'MYCOBACTERIUMCHELONAE', 'MYCOBACTERIUMSPECIES-RAPIDGROWER','MYCOBACTERIUMFORTUITUMSPECIESGROUP'],
              'CITROBACTER_SPECIES':['ZZZCITROBACTERFARMERI','CITROBACTERKOSERI','CITROBACTERSPECIES','CITROBACTERAMALONATICUS','ZZZCITROBACTERAMALONATICUS','CITROBACTERAMALONATICUSCOMPLEX','CITROBACTERFREUNDIICOMPLEX', 'CITROBACTERFREUNDII', 'CITROBACTERYOUNGAE', 'CITROBACTERBRAAKII'],
              'COAGNEGATIVE_STAPHYLOCOCCUS_SPECIES':['STAPHYLOCOCCUSLUGDUNENSIS', 'COAGNEGATIVESTAPHYLOCOCCUS', 'STAPHYLOCOCCUSEPIDERMIDIS', 'STAPHNEGNOTLUGDUNENSIS','STAPHYLOCOCCUSHAEMOLYTICUS','STAPHYLOCOCCUSSPECIES-COAGNEGATIVE,NOTSTAPHSAPROPHYTICUS'],
              'STAPHYLOCOCCUSAUREUS_SPECIES': ['STAPHAUREUS{MRSA}','STAPHAUREUS(COLONYVARIANT-SMALLCOLONYOROTHERMORPHOTYPE)','STAPHYLOCOCCUSAUREUS'],
              'PROVIDENCIA_SPECIES':['PROVIDENCIARETTGERI', 'PROVIDENCIASTUARTII', 'PROVIDENCIASPECIES'],
              'SAMONELLA_SPECIES':['SALMONELLATYPHI', 'SALMONELLASPECIES', 'SALMONELLAENTERICA'],
              'BACTEROIDES_FRAGILIS_SPECIES':['ZZZBACTEROIDESFRAGILISGROUP','BACTEROIDESFRAGILIS'],
              'BURKHOLDERIACEPACIA_SPECIES':['BURKHOLDERIACEPACIA', 'BURKHOLDERIACEPACIACOMPLEX', 'BURKHOLDERIACEPACIACOMPLEXGENOMOVARI', 'BURKHOLDERIACENOCEPACIA', 'BURKHOLDERIAVIETNAMIENSIS', 'BURKHOLDERIAGLADIOLI','BURKHOLDERIAMULTIVORANS'],
              'NOCARDIA_SPECIES':['NOCARDIAFARCINICA', 'NOCARDIANOVA', 'NOCARDIASPECIES', 'NOCARDIACYRIACIGEORGICA', 'NOCARDIATRANSVALENSISCOMPLEX', 'NOCARDIATRANSVALENSIS', 'NOCARDIAASTEROIDES', 'NORCARDIAWALLACEI','NOCARDIANOVACOMPLEX'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERTAYLORAE', 'ENTEROBACTERCANCEROGENUS', 'ENTEROBACTERASBURIAE', 'ENTEROBACTERSPECIES', 'ENTEROBACTERAMNIGENUS', 'ENTEROBACTERGERGOVIAE', 'ENTEROBACTERCLOACAE','ENTEROBACTERAMNIGENUS1'],
              'SERRATIA_SPECIES':['SERRATIAMARCESCENS', 'SERRATIARUBIDAEA', 'SERRATIALIQUEFACIENS', 'SERRATIAODORIFERA', 'SERRATIASPECIES', 'SERRATIAPLYMUTHICA'],
              'ACINETOBACTER_SPECIES':['ACINETOBACTERSPECIES', 'ACINETOBACTERBAUMANNIICOMPLEX', 'ACINETOBACTERBAUMANNII', 'ACINETOBACTERLWOFFI', 'ACINETOBACTERHAEMOLYTICUS'],
              'SPHINGOBACTERIUM_SPECIES':['SPHINGOBACTERIUMMULTIVORUM', 'SPHINGOBACTERIUMSPIRITIVORUM'],
              'RALSTONIA_SPECIES':['RALSTONIAMANNITOLILYTICA', 'RALSTONIASPECIES'],
              'AEROMONA_SPECIES':['AEROMONASCAVIAE', 'AEROMONASHYDROPHILAGROUP', 'ZZAEROMONASHYDROPHILACOMPLEX', 'AEROMONASVERONII', 'ZZAEROMONASCAVIAECOMPLEX', 'AEROMONASSPECIES','ZZAEROMONASVERONIICOMPLEX'],
              'CHRYSEOBACTERIUM_SPECIES':['CHRYSEOBACTERIUMINDOLOGENES', 'CHRYSEOBACTERIUMSPECIES'],
              'ACHROMOBACTER_SPECIES':['ACHROMOBACTERSPECIES', 'ACHROMOBACTERXYLOSOXIDANS'],
              'RAOULTELLA_SPECIES':['RAOULTELLA', 'RAOULTELLAORNITHINOLYTICA', 'RAOULTELLAPLANTICOLA'],
              'ELIZABETHKINGIA_SPECIES':['ELIZABETHKINGIASPECIES', 'ELIZABETHKINGIAMENINGOSEPTICA'],
              'SPHINGOMONAS_SPECIES':['SPHINGOMONASPAUCIMOBILIS/PARAPAUCIMOBILIS', 'SPHINGOMONAS'],
              'KLUYVERA_SPECIES':['KLUYVERACRYOCRESCENS', 'KLUYVERAASCORBATA', 'KLUYVERASPECIES'],
              'STREPTOCOCCUS_GROUPA':['STREP.GRPDNOTENTEROCOCCI','STREPTOCOCCUSPYOGENES(GROUPA)','STREPTOCOCCUSPYOGENES{GROUPA}', 'BETASTREPTOCOCCUSSPECIES'],
              'STREPTOCOCCUS_VIRIDANS/ALPHAHEMOLYTIC':['STREPTOCOCCUSORALIS','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC,NOTS.PNEUMO','STREPTOCOCCUSPNEUMONIAE','STREPTOCOCCUSSALIVARIUSGROUP','STREPTOCOCCUSSALIVARIUS','STREPTOCOCCUSMUTANS','STREPTOCOCCUSMUTANSGROUP','STREPTOCOCCUSGORDONII','STREPTOCOCCUSMITISGROUP','STREPTOCOCCUSCONSTELLATUS','STREPTOCOCCUSMITIS','STREPTOCOCCUSSANGUINIS','STREPTOCOCCUSSANGUIS','STREPTOCOCCUSANGINOSUSGROUP','STREPTOCOCCUSPARASANGUINIS','STREPTOCOCCUSINTERMEDIUS','VIRIDANSGROUPSTREPTOCOCCI', 'VIRIDANSGROUPSTREPTOCOCCINOTS.PNEUMONIAE', 'STREPTOCOCCUSANGINOSUS', 'STREPTOCOCCUSMITIS/STREPTOCOCCUSORALIS'],
              'STREPTOCOCCUS_GROUPB':['STREPTOCOCCUSAGALACTIAE(GROUPB)','STREPTOCOCCUSAGALACTIAE{GROUPB}'],
              'STREPTOCOCCUS_GROUPC':['BETASTREPTOCOCCUSGROUPC','STREPTOCOCCUSDYSGALACTIAE','STREPTOCOCCUSDYSGALACTIAESUBSP.EQUISIMILIS(GROUPC/GSTR]'],
              'STREPTOCOCCUS_GROUPD':['STREPTOCOCCUSGALLOLYTICUS,SUBSP.GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.PASTEURIANUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.PASTEURIANUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.GALLOLYTICUS','STREPTOCOCCUSBOVISGP','STREPTOCOCCUSBOVISGP', 'STREPTOCOCCUSBOVIS','STREPTOCOCCUSBOVISGP.'],
              'PSEUDOMONAS_SPECIES':['PSEUDOMONASFLUORESCENS','PSEUDOMONASFLUORESCENSGROUP','PSEUDOMONASPUTIDA','PSEUDOMONASPUTIDAGROUP','PSEUDOMONASSTUTZERI','PSEUDOMONASSTUTZERIGROUP','PSEUDOMONASMENDOCINA','PSEUDOMONASAERUGINOSA(NON-MUCOIDCF)','PSEUDOMONASAERUGINOSA','MUCOIDPSEUDOMONASAERUGINOSA'],
              'PSEUDOMONAS_NOT_AERUGINOSA':['NON-FERMENTINGGRAMNEGATIVERODS-NOTP.AERUGINOSA','PSEUDOMONASSPECIES-NOTP.AERUGINOSA','PSEUDOMONASORYZIHABITANS'],
              'CLOSTIDIUMN_SPECIES':['CLOSTRIDIUMCLOSTRIDIOFORME', 'CLOSTRIDIUMPARAPUTRIFICUM', 'ZZZCLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSORDELLII', 'CLOSTRIDIUMTERTIUM', 'CLOSTRIDIUMRAMOSUM', 'CLOSTRIDIUMSPECIES,NOTPERFRINGENS', 'CLOSTRIDIUMINNOCUUM', 'CLOSTRIDIUMSEPTICUM', 'CLOSTRIDIUMPERFRINGENS'],
              'PROTEUS_NOT_MIRABILIS':['ZZZPROTEUSPENNERI','ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERTAYLORAE','ENTEROBACTERCANCEROGENUS','ENTEROBACTERASBURIAE','ENTEROBACTERSPECIES','ENTEROBACTERCLOACAECOMPLEX','ENTEROBACTER_SPECIES','ENTEROBACTERAMNIGENUS1'],
              'FUSOBACTERIUM':['FUSOBACTERIUMNECROPHORUM', 'FUSOBACTERIUMSPECIES', 'FUSOBACTERIUMNUCLEATUM'],
              'LACTOBACILLUS':['LACTOBACILLUSRHAMNOSUS', 'LACTOBACILLUSSPECIES', 'LACTOBACILLUSCASEI'],
              'AEROCOCCUS':['AEROCOCCUSURINAE', 'AEROCOCCUSSANGUINICOLA','AEROCOCCUSSPECIES'],
              'MORAXELLA':['MORAXELLAOSLOENSIS','MORAXELLANON-LIQUEFACIENS','MORAXELLASPECIES'],
              'ALCALIGENES':['ALCALIGENESSPECIES','ALCALIGENESFAECALIS'],
              'ESCHERICHIA_NOT_COLI':['ESCHERICHIAFERGUSONII', 'ESCHERICHIAVULNERIS','ESCHERICHIAHERMANII'],
              'TSUKAMURELLA':['TSUKAMURELLASPECIES', 'TSUKAMURELLAPULMONIS'],
              'BACTEROIDES_SPECIES_NOT_FRAGILIS':['BACTEROIDESUREOLYTICUS', 'BACTEROIDESCACCAE', 'BACTEROIDESOVATUS', 'BACTEROIDESUNIFORMIS', 'BACTEROIDESVULGATUS', 'BACTEROIDESTHETAIOTAOMICRON', 'PARABACTEROIDESDISTASONIS', 'ZZZBACTEROIDESDISTASONIS', 'BACTEROIDESVULGATUS']}





for replace in swaps:
    print("replace: " + replace + " swaps: " + swaps[replace])
    data['organism'] = data['organism'].replace(replace,swaps[replace])


multiSwaps = {'CORYNEBACTERIUM_PATHOGENCY_MODERATE':['CORYNEBACTERIUMSTRIATUM', 'CORYNEBACTERIUMMACGINLEYI', 'CORYNEBACTERIUMJEIKEIUM', 'CORYNEBACTERIUMPSEUDODIPHTHERITICUM','CORYNEBACTERIUMUREALYTICUM'],
              'CORYNEBACTERIUM_PATHOGENCY_LOW':['CORYNEBACTERIUMPROPINQUUM', 'CORYNEBACTERIUMACCOLENS', 'CORYNEBACTERIUMAMYCOLATUM', 'DIPHTHEROIDS-CORYNEBACTERIUMSPECIES', 'CORYNEBAC.STRIATUM/AMYCOLATUM'],
              'KLEBSIELLA.PNEUMONIAE':['KLEBSIELLAOZAENAE', 'KLEBSIELLAPNEUMONIAESSP.OZAENAE', 'KLEBSIELLAAEROGENES', 'KLEBSIELLAOXYTOCA', 'KLEBSIELLAPNEUMONIAE', 'ZZZENTEROBACTERAEROGENES'],
              'ENTEROCOCCUS._GALLINARUM':['ENTEROCOCCUSGALLINARUM', 'ENTEROCOCCUSCASSELIFLAVUS'],
              'ENTEROCOCCUS_RARE_SPECIES':['ENTEROCOCCUSSPECIES', 'ENTEROCOCCUSAVIUM', 'ENTEROCOCCUSRAFFINOSUS', 'ENTEROCOCCUSDURANS/HIRAE', 'ENTEROCOCCUSDURANS'],
              'MYCOBACTERIUMAVIUM_COMPLEX(MAC)':['MYCOBACTERIUMAVIUMCOMPLEX','CHROMOGENICAFB,NOTM.TUBERCULOSIS'],
              'MYCOBACTERIUM_RAPID_GROWING(RGM)':['MYCOBACTERIUMIMMUNOGENUM','MYCOBACTERIUMNEOAURUM', 'ZZZMYCOBACTERIUMMUCOGENICUM', 'MYCOBACTERIUMABSCESSUSGROUP','MYCOBACTERIUMABSCESSUS', 'MYCOBACTERIUMFORTUITUM', 'MYCOBACTERIUMCHELONAE', 'MYCOBACTERIUMSPECIES-RAPIDGROWER','MYCOBACTERIUMFORTUITUMSPECIESGROUP'],
              'CITROBACTER_FREUNDII_COMPLEX':['CITROBACTERFREUNDIICOMPLEX', 'CITROBACTERFREUNDII', 'CITROBACTERYOUNGAE', 'CITROBACTERBRAAKII'],
              'CITROBACTER_AMALONATICUS':['CITROBACTERAMALONATICUS','ZZZCITROBACTERAMALONATICUS','CITROBACTERAMALONATICUSCOMPLEX'],
              'COAGNEGATIVE_STAPHYLOCOCCUS_SPECIES':['STAPHYLOCOCCUSLUGDUNENSIS', 'COAGNEGATIVESTAPHYLOCOCCUS', 'STAPHYLOCOCCUSEPIDERMIDIS', 'STAPHNEGNOTLUGDUNENSIS','STAPHYLOCOCCUSHAEMOLYTICUS','STAPHYLOCOCCUSSPECIES-COAGNEGATIVE,NOTSTAPHSAPROPHYTICUS'],
              'STAPHYLOCOCCUSAUREUS_SPECIES': ['STAPHAUREUS{MRSA}','STAPHAUREUS(COLONYVARIANT-SMALLCOLONYOROTHERMORPHOTYPE)','STAPHYLOCOCCUSAUREUS'],
              'PROVIDENCIA_SPECIES':['PROVIDENCIARETTGERI', 'PROVIDENCIASTUARTII', 'PROVIDENCIASPECIES'],
              'SAMONELLA_SPECIES':['SALMONELLATYPHI', 'SALMONELLASPECIES', 'SALMONELLAENTERICA'],
              'BACTEROIDES_FRAGILIS_SPECIES':['ZZZBACTEROIDESFRAGILISGROUP','BACTEROIDESFRAGILIS'],
              'BURKHOLDERIACEPACIA_SPECIES':['BURKHOLDERIACEPACIA', 'BURKHOLDERIACEPACIACOMPLEX', 'BURKHOLDERIACEPACIACOMPLEXGENOMOVARI', 'BURKHOLDERIACENOCEPACIA', 'BURKHOLDERIAVIETNAMIENSIS', 'BURKHOLDERIAGLADIOLI','BURKHOLDERIAMULTIVORANS'],
              'NOCARDIA_SPECIES':['NOCARDIAFARCINICA', 'NOCARDIANOVA', 'NOCARDIASPECIES', 'NOCARDIACYRIACIGEORGICA', 'NOCARDIATRANSVALENSISCOMPLEX', 'NOCARDIATRANSVALENSIS', 'NOCARDIAASTEROIDES', 'NORCARDIAWALLACEI','NOCARDIANOVACOMPLEX'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERCLOACAECOMPLEX(CARBAPENEMRESISTANT)','ENTEROBACTERTAYLORAE', 'ENTEROBACTERCANCEROGENUS', 'ENTEROBACTERASBURIAE', 'ENTEROBACTERSPECIES', 'ENTEROBACTERAMNIGENUS', 'ENTEROBACTERGERGOVIAE', 'ENTEROBACTERCLOACAE','ENTEROBACTERAMNIGENUS1'],
              'SERRATIA_SPECIES':['SERRATIAMARCESCENS', 'SERRATIARUBIDAEA', 'SERRATIALIQUEFACIENS', 'SERRATIAODORIFERA', 'SERRATIASPECIES', 'SERRATIAPLYMUTHICA'],
              'ACINETOBACTER_SPECIES':['ACINETOBACTERSPECIES', 'ACINETOBACTERBAUMANNIICOMPLEX', 'ACINETOBACTERBAUMANNII', 'ACINETOBACTERLWOFFI', 'ACINETOBACTERHAEMOLYTICUS'],
              'SPHINGOBACTERIUM_SPECIES':['SPHINGOBACTERIUMMULTIVORUM', 'SPHINGOBACTERIUMSPIRITIVORUM'],
              'RALSTONIA_SPECIES':['RALSTONIAMANNITOLILYTICA', 'RALSTONIASPECIES'],
              'AEROMONA_SPECIES':['AEROMONASCAVIAE', 'AEROMONASHYDROPHILAGROUP', 'ZZAEROMONASHYDROPHILACOMPLEX', 'AEROMONASVERONII', 'ZZAEROMONASCAVIAECOMPLEX', 'AEROMONASSPECIES','ZZAEROMONASVERONIICOMPLEX'],
              'CHRYSEOBACTERIUM_SPECIES':['CHRYSEOBACTERIUMINDOLOGENES', 'CHRYSEOBACTERIUMSPECIES'],
              'ACHROMOBACTER_SPECIES':['ACHROMOBACTERSPECIES', 'ACHROMOBACTERXYLOSOXIDANS'],
              'RAOULTELLA_SPECIES':['RAOULTELLA', 'RAOULTELLAORNITHINOLYTICA', 'RAOULTELLAPLANTICOLA'],
              'ELIZABETHKINGIA_SPECIES':['ELIZABETHKINGIASPECIES', 'ELIZABETHKINGIAMENINGOSEPTICA'],
              'SPHINGOMONAS_SPECIES':['SPHINGOMONASPAUCIMOBILIS/PARAPAUCIMOBILIS', 'SPHINGOMONAS'],
              'KLUYVERA_SPECIES':['KLUYVERACRYOCRESCENS', 'KLUYVERAASCORBATA', 'KLUYVERASPECIES'],
              'STREPTOCOCCUS_GROUPA':['STREP.GRPDNOTENTEROCOCCI','STREPTOCOCCUSPYOGENES(GROUPA)','STREPTOCOCCUSPYOGENES{GROUPA}', 'BETASTREPTOCOCCUSSPECIES'],
              'STREPTOCOCCUS_VIRIDANS/ALPHAHEMOLYTIC':['STREPTOCOCCUSORALIS','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC,NOTS.PNEUMO','STREPTOCOCCUSPNEUMONIAE','STREPTOCOCCUSSALIVARIUSGROUP','STREPTOCOCCUSSALIVARIUS','STREPTOCOCCUSMUTANS','STREPTOCOCCUSMUTANSGROUP','STREPTOCOCCUSGORDONII','STREPTOCOCCUSMITISGROUP','STREPTOCOCCUSCONSTELLATUS','STREPTOCOCCUSMITIS','STREPTOCOCCUSSANGUINIS','STREPTOCOCCUSSANGUIS','STREPTOCOCCUSANGINOSUSGROUP','STREPTOCOCCUSPARASANGUINIS','STREPTOCOCCUSINTERMEDIUS','VIRIDANSGROUPSTREPTOCOCCI', 'VIRIDANSGROUPSTREPTOCOCCINOTS.PNEUMONIAE', 'STREPTOCOCCUSANGINOSUS', 'STREPTOCOCCUSMITIS/STREPTOCOCCUSORALIS'],
              'STREPTOCOCCUS_GROUPB':['STREPTOCOCCUSAGALACTIAE(GROUPB)','STREPTOCOCCUSAGALACTIAE{GROUPB}'],
              'STREPTOCOCCUS_GROUPC':['BETASTREPTOCOCCUSGROUPC','STREPTOCOCCUSDYSGALACTIAE','STREPTOCOCCUSDYSGALACTIAESUBSP.EQUISIMILIS(GROUPC/GSTR]'],
              'STREPTOCOCCUS_GROUPD':['STREPTOCOCCUSGALLOLYTICUS,SUBSP.GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.PASTEURIANUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.PASTEURIANUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.GALLOLYTICUS','STREPTOCOCCUSBOVISGP','STREPTOCOCCUSBOVISGP', 'STREPTOCOCCUSBOVIS','STREPTOCOCCUSBOVISGP.'],
              'PSEUDOMONAS_SPECIES':['PSEUDOMONASFLUORESCENS','PSEUDOMONASFLUORESCENSGROUP','PSEUDOMONASPUTIDA','PSEUDOMONASPUTIDAGROUP','PSEUDOMONASSTUTZERI','PSEUDOMONASSTUTZERIGROUP','PSEUDOMONASMENDOCINA','PSEUDOMONASAERUGINOSA(NON-MUCOIDCF)','PSEUDOMONASAERUGINOSA','MUCOIDPSEUDOMONASAERUGINOSA'],
              'PSEUDOMONAS_NOT_AERUGINOSA':['NON-FERMENTINGGRAMNEGATIVERODS-NOTP.AERUGINOSA','PSEUDOMONASSPECIES-NOTP.AERUGINOSA','PSEUDOMONASORYZIHABITANS'],
              'CLOSTIDIUMN_SPECIES':['CLOSTRIDIUMCLOSTRIDIOFORME', 'CLOSTRIDIUMPARAPUTRIFICUM', 'ZZZCLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSORDELLII', 'CLOSTRIDIUMTERTIUM', 'CLOSTRIDIUMRAMOSUM', 'CLOSTRIDIUMSPECIES,NOTPERFRINGENS', 'CLOSTRIDIUMINNOCUUM', 'CLOSTRIDIUMSEPTICUM', 'CLOSTRIDIUMPERFRINGENS'],
              'PROTEUS_NOT_MIRABILIS':['ZZZPROTEUSPENNERI','ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERTAYLORAE','ENTEROBACTERCANCEROGENUS','ENTEROBACTERASBURIAE','ENTEROBACTERSPECIES','ENTEROBACTERCLOACAECOMPLEX','ENTEROBACTER_SPECIES','ENTEROBACTERAMNIGENUS1'],
              'FUSOBACTERIUM':['FUSOBACTERIUMNECROPHORUM', 'FUSOBACTERIUMSPECIES', 'FUSOBACTERIUMNUCLEATUM'],
              'LACTOBACILLUS':['LACTOBACILLUSRHAMNOSUS', 'LACTOBACILLUSSPECIES', 'LACTOBACILLUSCASEI'],
              'AEROCOCCUS':['AEROCOCCUSURINAE', 'AEROCOCCUSSANGUINICOLA','AEROCOCCUSSPECIES'],
              'MORAXELLA':['MORAXELLAOSLOENSIS','MORAXELLANON-LIQUEFACIENS','MORAXELLASPECIES'],
              'ALCALIGENES':['ALCALIGENESSPECIES','ALCALIGENESFAECALIS'],
              'ESCHERICHIA_NOT_COLI':['ESCHERICHIAFERGUSONII', 'ESCHERICHIAVULNERIS','ESCHERICHIAHERMANII'],
              'TSUKAMURELLA':['TSUKAMURELLASPECIES', 'TSUKAMURELLAPULMONIS'],
              'BACTEROIDES_SPECIES':['BACTEROIDESUREOLYTICUS', 'BACTEROIDESCACCAE', 'BACTEROIDESOVATUS', 'BACTEROIDESUNIFORMIS', 'BACTEROIDESVULGATUS', 'BACTEROIDESTHETAIOTAOMICRON', 'PARABACTEROIDESDISTASONIS', 'ZZZBACTEROIDESDISTASONIS', 'BACTEROIDESVULGATUS']}

data['organism'] = data['organism'].replace([r'\(CARBAPENEMRESISTANT\)','-VANCORESISTANT'],'',regex=True)

data['organism']=data['organism'].replace(['PSEUDOMONAS_NOT_AERUGINOSA','PSEUDOMONASSPECIES-FLUORESCENS/PUTIDAGROUP','OCHROBACTRUMANTHROPI', 'OCHROBACTRUM','MYROIDESSPECIES','BACILLUSSPECIES','STAPHYLOCOCCUSSPECIES-NOTSTAPH.AUREUS','ESCHERICHIASPECIES','CORYNEBACTERIUMSPECIES','ARCANOBACTERIUMHAEMOLYTICUM','PAENIBACILLUSSPECIES','BACTEROIDESSPECIES','LECLERCIAADECARBOXYLATA','STAPHYLOCOCCUSSPECIES,COAGPENDING','STAPHYLOCOCCUSSPECIES','CORYNEBACTERIUMDIPTHERIAE','CORYNEBACTERIUMSPECIES,NOTC.UREALYTICUM','BORDETELLABRONCHISEPTICA','PSEUDOMONASSPECIES','BACTEROIDESSPECIESNOTFRAGILIS','ANAEROBICGRAMPOSITIVECOCCI','PASTEURELLAMULTOCIDA','GORDONIASPECIES','ACTINOMYCESSPECIES','DERMABACTERHOMINIS','STREP.GRPDNOTENTEROCOCCI','MICROCOCCUSSPECIES','CULTUREPOSITIVEGRAMPOSITIVECOCCI','DIPHTHEROIDS-CORYNEBACTERIUMSPECIES','GRAMNEGATIVERODS-NONFERM,UNIDENTIFIED','ACIDFASTBACILLI','ANAEROBICGRAMPOSITIVERODS','ENTERICGRAMNEGATIVERODS','CULTUREPOSITIVEGRAMNEGATIVECOCCI','GRAMPOSITIVERODS','GRAMNEGATIVERODS','NONSPORE-FORMINGANAEROBICGRAMPOSITIVERODS','LACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS-UNIDENTIFIED','NONLACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS','ACIDFASTBACILLIDETECTEDINLIQUIDMEDIUM','PARABACTEROIDESSPECIES','LISTERIASPECIES','LISTERIAMONOCYTOGENES','STREPTOCOCCUSSPECIES', 'KLEBSIELLASPECIES', 'PROTEUSSPECIES', 'ARCANOBACTERIUMHAEMOLYTICUM ', 'CRONOBACTERSAKAZAKII', 'CHRYSEOMONASLUTEOLA', 'LEUCONOSTOCSPECIES', 'BETASTREPTOCOCCUSGROUPG', 'PREVOTELLASPECIES', 'PEDIOCOCCUSSP.','ABIOTROPHIASPECIES(ORGRANULICATELLASPECIES)', 'CAMPYLOBACTERSPECIES', 'HAFNIA','RAHNELLA', 'ANAEROBICGRAMNEGATIVERODS', 'SHEWANELLAPUTREFACIENS', 'SCHISTOSOMAHAEMATOBIUMOVA', 'MYCOBACTERIUMSPECIES',' LECLERCIAADECARBOXYLATA', 'EGGERTHELLALENTA', 'YERSINIAENTEROCOLITICA','LACTOCOCCUSSPECIES', 'FLAVOBACTERIUMSPECIES', 'BREVUNDIMONAS', 'PEPTOSTREPTOCOCCUSSPECIES', 'BREVIBACTERIUMSPECIES', 'ZZZBACTEROIDESNOTB.FRAGILISGRP', 'VEILLONELLASPECIES', 'SHIGELLASPECIES', 'EUBACTERIUMLENTUM', 'COMAMONASACIDOVORANS', 'EWINGELLAAMERICANA', 'OLIGELLAURETHRALIS', 'ZZZPROPIONIBACTERIUMACNES', 'HAEMOPHILUSACTINOMYCETEMCOMITANS', 'MICROBACTERIUMSPECIES',],np.nan)
data = data.dropna()
for replaceM in multiSwaps:
    data['organism'] = data['organism'].replace(multiSwaps[replaceM], replaceM)
data['organism']=data['organism'].replace(['MORAXELLA','AEROCOCCUS','PSEUDOMONAS_NOT_AERUGINOSA','PSEUDOMONASSPECIES-FLUORESCENS/PUTIDAGROUP','OCHROBACTRUMANTHROPI', 'OCHROBACTRUM','MYROIDESSPECIES','BACILLUSSPECIES','STAPHYLOCOCCUSSPECIES-NOTSTAPH.AUREUS','ESCHERICHIASPECIES','CORYNEBACTERIUMSPECIES','ARCANOBACTERIUMHAEMOLYTICUM','PAENIBACILLUSSPECIES','BACTEROIDESSPECIES','LECLERCIAADECARBOXYLATA','STAPHYLOCOCCUSSPECIES,COAGPENDING','STAPHYLOCOCCUSSPECIES','CORYNEBACTERIUMDIPTHERIAE','CORYNEBACTERIUMSPECIES,NOTC.UREALYTICUM','BORDETELLABRONCHISEPTICA','PSEUDOMONASSPECIES','BACTEROIDESSPECIESNOTFRAGILIS','ANAEROBICGRAMPOSITIVECOCCI','PASTEURELLAMULTOCIDA','GORDONIASPECIES','ACTINOMYCESSPECIES','DERMABACTERHOMINIS','STREP.GRPDNOTENTEROCOCCI','MICROCOCCUSSPECIES','CULTUREPOSITIVEGRAMPOSITIVECOCCI','DIPHTHEROIDS-CORYNEBACTERIUMSPECIES','GRAMNEGATIVERODS-NONFERM,UNIDENTIFIED','ACIDFASTBACILLI','ANAEROBICGRAMPOSITIVERODS','ENTERICGRAMNEGATIVERODS','CULTUREPOSITIVEGRAMNEGATIVECOCCI','GRAMPOSITIVERODS','GRAMNEGATIVERODS','NONSPORE-FORMINGANAEROBICGRAMPOSITIVERODS','LACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS-UNIDENTIFIED','NONLACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS','ACIDFASTBACILLIDETECTEDINLIQUIDMEDIUM','PARABACTEROIDESSPECIES','LISTERIASPECIES','LISTERIAMONOCYTOGENES','STREPTOCOCCUSSPECIES', 'KLEBSIELLASPECIES', 'PROTEUSSPECIES', 'ARCANOBACTERIUMHAEMOLYTICUM ', 'CRONOBACTERSAKAZAKII', 'CHRYSEOMONASLUTEOLA', 'LEUCONOSTOCSPECIES', 'BETASTREPTOCOCCUSGROUPG', 'PREVOTELLASPECIES', 'PEDIOCOCCUSSP.','ABIOTROPHIASPECIES(ORGRANULICATELLASPECIES)', 'CAMPYLOBACTERSPECIES', 'HAFNIA','RAHNELLA', 'ANAEROBICGRAMNEGATIVERODS', 'SHEWANELLAPUTREFACIENS', 'SCHISTOSOMAHAEMATOBIUMOVA', 'MYCOBACTERIUMSPECIES',' LECLERCIAADECARBOXYLATA', 'EGGERTHELLALENTA', 'YERSINIAENTEROCOLITICA','LACTOCOCCUSSPECIES', 'FLAVOBACTERIUMSPECIES', 'BREVUNDIMONAS', 'PEPTOSTREPTOCOCCUSSPECIES', 'BREVIBACTERIUMSPECIES', 'ZZZBACTEROIDESNOTB.FRAGILISGRP', 'VEILLONELLASPECIES', 'SHIGELLASPECIES', 'EUBACTERIUMLENTUM', 'COMAMONASACIDOVORANS', 'EWINGELLAAMERICANA', 'OLIGELLAURETHRALIS', 'ZZZPROPIONIBACTERIUMACNES', 'HAEMOPHILUSACTINOMYCETEMCOMITANS', 'MICROBACTERIUMSPECIES',],np.nan)
data = data.dropna()
print(len(data['organism'].unique()))
print(data.shape)
for organism,count in data['culture_description'].value_counts().items():
    print("organism: "+organism+ " "+str(count))




ordTranslateAge = OrdinalEncoder(categories = [['18-24 years','25-34 years','35-44 years','45-54 years','55-64 years','65-74 years','75-84 years','85-89 years','above 90' ]])

weights = {}
for organismName in data['organism'].unique():
    weights[organismName]=1


weights['ACHROMOBACTER_SPECIES'] = 1.5
weights['SPHINGOMONAS_SPECIES'] = 1.5
weights['SPHINGOBACTERIUM_SPECIES'] = 1.5
weights['HAFNIAALVEI'] = 1.5

'''
multiSwaps = {'CORYNEBACTERIUM':['CORYNEBACTERIUMSTRIATUM', 'CORYNEBACTERIUMMACGINLEYI', 'CORYNEBACTERIUMJEIKEIUM', 'CORYNEBACTERIUMPSEUDODIPHTHERITICUM','CORYNEBACTERIUMUREALYTICUM','CORYNEBACTERIUMPROPINQUUM', 'CORYNEBACTERIUMACCOLENS', 'CORYNEBACTERIUMAMYCOLATUM', 'DIPHTHEROIDS-CORYNEBACTERIUMSPECIES', 'CORYNEBAC.STRIATUM/AMYCOLATUM'],
              'KLEBSIELLA.PNEUMONIAE':['KLEBSIELLAOZAENAE', 'KLEBSIELLAPNEUMONIAESSP.OZAENAE', 'KLEBSIELLAAEROGENES', 'KLEBSIELLAOXYTOCA', 'KLEBSIELLAPNEUMONIAE', 'ZZZENTEROBACTERAEROGENES'],
              'ENTEROCOCCUS._GALLINARUM':['ENTEROCOCCUSGALLINARUM', 'ENTEROCOCCUSCASSELIFLAVUS'],
              'ENTEROCOCCUS_RARE_SPECIES':['ENTEROCOCCUSSPECIES', 'ENTEROCOCCUSAVIUM', 'ENTEROCOCCUSRAFFINOSUS', 'ENTEROCOCCUSDURANS/HIRAE', 'ENTEROCOCCUSDURANS'],
              'MYCOBACTERIUMAVIUM_COMPLEX(MAC)':['MYCOBACTERIUMAVIUMCOMPLEX','CHROMOGENICAFB,NOTM.TUBERCULOSIS'],
              'MYCOBACTERIUM_RAPID_GROWING(RGM)':['MYCOBACTERIUMIMMUNOGENUM','MYCOBACTERIUMNEOAURUM', 'ZZZMYCOBACTERIUMMUCOGENICUM', 'MYCOBACTERIUMABSCESSUSGROUP','MYCOBACTERIUMABSCESSUS', 'MYCOBACTERIUMFORTUITUM', 'MYCOBACTERIUMCHELONAE', 'MYCOBACTERIUMSPECIES-RAPIDGROWER','MYCOBACTERIUMFORTUITUMSPECIESGROUP'],
              'CITROBACTER':['CITROBACTERKOSERI','ZZZCITROBACTERFARMERI','CITROBACTER_FREUNDII_COMPLEX','CITROBACTER_AMALONATICUS','CITROBACTERSPECIES','CITROBACTERFREUNDIICOMPLEX', 'CITROBACTERFREUNDII', 'CITROBACTERYOUNGAE', 'CITROBACTERBRAAKII','CITROBACTERAMALONATICUS','ZZZCITROBACTERAMALONATICUS','CITROBACTERAMALONATICUSCOMPLEX'],
              'COAGNEGATIVE_STAPHYLOCOCCUS_SPECIES':['STAPHYLOCOCCUSLUGDUNENSIS', 'COAGNEGATIVESTAPHYLOCOCCUS', 'STAPHYLOCOCCUSEPIDERMIDIS', 'STAPHNEGNOTLUGDUNENSIS','STAPHYLOCOCCUSHAEMOLYTICUS','STAPHYLOCOCCUSSPECIES-COAGNEGATIVE,NOTSTAPHSAPROPHYTICUS'],
              'STAPHYLOCOCCUSAUREUS_SPECIES': ['STAPHAUREUS{MRSA}','STAPHAUREUS(COLONYVARIANT-SMALLCOLONYOROTHERMORPHOTYPE)','STAPHYLOCOCCUSAUREUS'],
              'PROVIDENCIA_SPECIES':['PROVIDENCIARETTGERI', 'PROVIDENCIASTUARTII', 'PROVIDENCIASPECIES'],
              'SAMONELLA_SPECIES':['SALMONELLATYPHI', 'SALMONELLASPECIES', 'SALMONELLAENTERICA'],
              'BACTEROIDES_FRAGILIS_SPECIES':['ZZZBACTEROIDESFRAGILISGROUP','BACTEROIDESFRAGILIS'],
              'BURKHOLDERIACEPACIA_SPECIES':['BURKHOLDERIACEPACIA', 'BURKHOLDERIACEPACIACOMPLEX', 'BURKHOLDERIACEPACIACOMPLEXGENOMOVARI', 'BURKHOLDERIACENOCEPACIA', 'BURKHOLDERIAVIETNAMIENSIS', 'BURKHOLDERIAGLADIOLI','BURKHOLDERIAMULTIVORANS'],
              'NOCARDIA_SPECIES':['NOCARDIAFARCINICA', 'NOCARDIANOVA', 'NOCARDIASPECIES', 'NOCARDIACYRIACIGEORGICA', 'NOCARDIATRANSVALENSISCOMPLEX', 'NOCARDIATRANSVALENSIS', 'NOCARDIAASTEROIDES', 'NORCARDIAWALLACEI','NOCARDIANOVACOMPLEX'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERGERGOVIAE','ENTEROBACTERCLOACAE','ENTEROBACTERTAYLORAE', 'ENTEROBACTERCANCEROGENUS', 'ENTEROBACTERASBURIAE', 'ENTEROBACTERSPECIES', 'ENTEROBACTERAMNIGENUS', 'ENTEROBACTERGERGOVIAE', 'ENTEROBACTERCLOACAE','ENTEROBACTERAMNIGENUS1'],
              'SERRATIA_SPECIES':['SERRATIAMARCESCENS', 'SERRATIARUBIDAEA', 'SERRATIALIQUEFACIENS', 'SERRATIAODORIFERA', 'SERRATIASPECIES', 'SERRATIAPLYMUTHICA'],
              'ACINETOBACTER_SPECIES':['ACINETOBACTERSPECIES', 'ACINETOBACTERBAUMANNIICOMPLEX', 'ACINETOBACTERBAUMANNII', 'ACINETOBACTERLWOFFI', 'ACINETOBACTERHAEMOLYTICUS'],
              'SPHINGO_SPECIES':['SPHINGOBACTERIUMMULTIVORUM', 'SPHINGOBACTERIUMSPIRITIVORUM','SPHINGOMONASPAUCIMOBILIS/PARAPAUCIMOBILIS', 'SPHINGOMONAS'],
              'RALSTONIA_SPECIES':['RALSTONIAMANNITOLILYTICA', 'RALSTONIASPECIES'],
              'AEROMONA_SPECIES':['AEROMONASCAVIAE', 'AEROMONASHYDROPHILAGROUP', 'ZZAEROMONASHYDROPHILACOMPLEX', 'AEROMONASVERONII', 'ZZAEROMONASCAVIAECOMPLEX', 'AEROMONASSPECIES','ZZAEROMONASVERONIICOMPLEX'],
              'CHRYSEOBACTERIUM_SPECIES':['CHRYSEOBACTERIUMINDOLOGENES', 'CHRYSEOBACTERIUMSPECIES'],
              'ACHROMOBACTER_SPECIES':['ACHROMOBACTERSPECIES', 'ACHROMOBACTERXYLOSOXIDANS'],
              'RAOULTELLA_SPECIES':['RAOULTELLA', 'RAOULTELLAORNITHINOLYTICA', 'RAOULTELLAPLANTICOLA'],
              'ELIZABETHKINGIA_SPECIES':['ELIZABETHKINGIASPECIES', 'ELIZABETHKINGIAMENINGOSEPTICA'],
              'KLUYVERA_SPECIES':['KLUYVERACRYOCRESCENS', 'KLUYVERAASCORBATA', 'KLUYVERASPECIES'],
              'STREPTOCOCCUS_GROUPA':['STREP.GRPDNOTENTEROCOCCI','STREPTOCOCCUSPYOGENES(GROUPA)','STREPTOCOCCUSPYOGENES{GROUPA}', 'BETASTREPTOCOCCUSSPECIES'],
              'STREPTOCOCCUS_VIRIDANS/ALPHAHEMOLYTIC':['STREPTOCOCCUSORALIS','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC,NOTS.PNEUMO','STREPTOCOCCUSPNEUMONIAE','STREPTOCOCCUSSALIVARIUSGROUP','STREPTOCOCCUSSALIVARIUS','STREPTOCOCCUSMUTANS','STREPTOCOCCUSMUTANSGROUP','STREPTOCOCCUSGORDONII','STREPTOCOCCUSMITISGROUP','STREPTOCOCCUSCONSTELLATUS','STREPTOCOCCUSMITIS','STREPTOCOCCUSSANGUINIS','STREPTOCOCCUSSANGUIS','STREPTOCOCCUSANGINOSUSGROUP','STREPTOCOCCUSPARASANGUINIS','STREPTOCOCCUSINTERMEDIUS','VIRIDANSGROUPSTREPTOCOCCI', 'VIRIDANSGROUPSTREPTOCOCCINOTS.PNEUMONIAE', 'STREPTOCOCCUSANGINOSUS', 'STREPTOCOCCUSMITIS/STREPTOCOCCUSORALIS'],
              'STREPTOCOCCUS_GROUPB':['STREPTOCOCCUSAGALACTIAE(GROUPB)','STREPTOCOCCUSAGALACTIAE{GROUPB}'],
              'STREPTOCOCCUS_GROUPC':['BETASTREPTOCOCCUSGROUPC','STREPTOCOCCUSDYSGALACTIAE','STREPTOCOCCUSDYSGALACTIAESUBSP.EQUISIMILIS(GROUPC/GSTR]'],
              'STREPTOCOCCUS_GROUPD':['ZZZSTREPTOCOCCUS GALLOLYTICUS SUBSP. GALLOLYTICUS','STREPTOCOCCUS GALLOLYTICUS, SUBSP. GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.PASTEURIANUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.PASTEURIANUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.GALLOLYTICUS','STREPTOCOCCUSBOVISGP','STREPTOCOCCUSBOVISGP', 'STREPTOCOCCUSBOVIS','STREPTOCOCCUSBOVISGP.'],
              'PSEUDOMONAS_SPECIES':['PSEUDOMONAS MENDOCINA','NON-FERMENTINGGRAMNEGATIVERODS-NOTP.AERUGINOSA','PSEUDOMONASSPECIES-NOTP.AERUGINOSA','PSEUDOMONASORYZIHABITANS','PSEUDOMONASFLUORESCENS','PSEUDOMONASFLUORESCENSGROUP','PSEUDOMONASPUTIDA','PSEUDOMONASPUTIDAGROUP','PSEUDOMONASSTUTZERI','PSEUDOMONASSTUTZERIGROUP','PSEUDOMONASMENDOCINA','PSEUDOMONASAERUGINOSA(NON-MUCOIDCF)','PSEUDOMONASAERUGINOSA','MUCOIDPSEUDOMONASAERUGINOSA'],
              'CLOSTIDIUMN_SPECIES':['CLOSTRIDIUMCLOSTRIDIOFORME', 'CLOSTRIDIUMPARAPUTRIFICUM', 'ZZZCLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSORDELLII', 'CLOSTRIDIUMTERTIUM', 'CLOSTRIDIUMRAMOSUM', 'CLOSTRIDIUMSPECIES,NOTPERFRINGENS', 'CLOSTRIDIUMINNOCUUM', 'CLOSTRIDIUMSEPTICUM', 'CLOSTRIDIUMPERFRINGENS'],
              'PROTEUS_NOT_MIRABILIS':['ZZZPROTEUSPENNERI','ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERGERGOVIAE','ENTEROBACTERCLOACAE','ENTEROBACTERTAYLORAE','ENTEROBACTERCANCEROGENUS','ENTEROBACTERASBURIAE','ENTEROBACTERSPECIES','ENTEROBACTERCLOACAECOMPLEX','ENTEROBACTER_SPECIES','ENTEROBACTERAMNIGENUS1'],
              'FUSOBACTERIUM':['FUSOBACTERIUMNECROPHORUM', 'FUSOBACTERIUMSPECIES', 'FUSOBACTERIUMNUCLEATUM'],
              'LACTOBACILLUS':['LACTOBACILLUSRHAMNOSUS', 'LACTOBACILLUSSPECIES', 'LACTOBACILLUSCASEI'],
              'AEROCOCCUS':['AEROCOCCUS SPECIES','AEROCOCCUSURINAE', 'AEROCOCCUSSANGUINICOLA','AEROCOCCUSSPECIES'],
              'ALCALIGENES':['ALCALIGENESSPECIES','ALCALIGENESFAECALIS'],
              'ESCHERICHIA_NOT_COLI':['ESCHERICHIAFERGUSONII', 'ESCHERICHIAVULNERIS','ESCHERICHIAHERMANII'],
              'TSUKAMURELLA':['TSUKAMURELLASPECIES', 'TSUKAMURELLAPULMONIS'],
              'PANTOEA':['PANTOEAAGGLOMERANS','PANTOEASPECIES'],
              'BACTEROIDES_NOTFRAGILIS':['BACTEROIDES OVATUS','ZZZBACTEROIDES NOT B. FRAGILIS GRP','BACTEROIDES UNIFORMIS','BACTEROIDES UREOLYTICUS ','BACTEROIDESUREOLYTICUS', 'BACTEROIDESCACCAE', 'BACTEROIDESOVATUS', 'BACTEROIDESUNIFORMIS', 'BACTEROIDESVULGATUS', 'BACTEROIDESTHETAIOTAOMICRON', 'PARABACTEROIDESDISTASONIS', 'ZZZBACTEROIDESDISTASONIS', 'BACTEROIDESVULGATUS'],
              'MORAXELLA':['MORAXELLAOSLOENSIS','MORAXELLANON-LIQUEFACIENS','MORAXELLASPECIES']
              }
#'PSEUDOMONAS_NOT_AERUGINOSA','PSEUDOMONASSPECIES-FLUORESCENS/PUTIDAGROUP', ADDED TO PSEUDOMONAS REMOVED FROM REMOVE
print(data.size)
data=data.drop(['antibiotic','susceptibility'],axis=1)
data= data.drop_duplicates()
print(data.size)

data =data.drop(['anon_id','pat_enc_csn_id_coded' ,'order_proc_id_coded'],axis=1)

#data['agregatedComorbidtyIndex'] = data[['charlsonCondition_anymalignancy/lymphoma/leukemia','charlsonCondition_cerebrovascularDisease','charlsonCondition_chronicPulmonaryDisease','charlsonCondition_congestiveHeartFailure','charlsonCondition_diabetesnoChronicComplication','charlsonCondition_diabeteswEndOrganDamage','charlsonCondition_hematologicDisease','charlsonCondition_metastaticSolidTumour','charlsonCondition_mildLiverDisease','charlsonCondition_moderateoSevereLiverDisease','charlsonCondition_myocardialInfraction','charlsonCondition_peripheralVascularDisease','charlsonCondition_renalDisease','charlsonCondition_rheumaticDisease']]
cols = ['charlsonCondition_anymalignancy/lymphoma/leukemia','charlsonCondition_cerebrovascularDisease','charlsonCondition_chronicPulmonaryDisease','charlsonCondition_congestiveHeartFailure','charlsonCondition_diabetesnoChronicComplication','charlsonCondition_diabeteswEndOrganDamage','charlsonCondition_hematologicDisease','charlsonCondition_metastaticSolidTumour','charlsonCondition_mildLiverDisease','charlsonCondition_moderateoSevereLiverDisease','charlsonCondition_myocardialInfraction','charlsonCondition_peripheralVascularDisease','charlsonCondition_renalDisease','charlsonCondition_rheumaticDisease']

data['organism'] = data['organism'].str.replace(' ','')
data['organism']=data['organism'].replace(['PSEUDOMONAS_NOT_AERUGINOSA','PSEUDOMONASSPECIES-FLUORESCENS/PUTIDAGROUP','GRAM NEGATIVE RODS','ZZZPROPIONIBACTERIUM ACNES','PASTEURELLA MULTOCIDA','HAEMOPHILUS ACTINOMYCETEMCOMITANS','ANAEROBIC GRAM NEGATIVE RODS','PAENIBACILLUS SPECIES','OCHROBACTRUMANTHROPI', 'OCHROBACTRUM','MYROIDESSPECIES','BACILLUSSPECIES','STAPHYLOCOCCUSSPECIES-NOTSTAPH.AUREUS','ESCHERICHIASPECIES','CORYNEBACTERIUMSPECIES','ARCANOBACTERIUMHAEMOLYTICUM','PAENIBACILLUSSPECIES','BACTEROIDESSPECIES','LECLERCIAADECARBOXYLATA','STAPHYLOCOCCUSSPECIES,COAGPENDING','STAPHYLOCOCCUSSPECIES','CORYNEBACTERIUMDIPTHERIAE','CORYNEBACTERIUMSPECIES,NOTC.UREALYTICUM','BORDETELLABRONCHISEPTICA','PSEUDOMONASSPECIES','BACTEROIDESSPECIESNOTFRAGILIS','ANAEROBICGRAMPOSITIVECOCCI','PASTEURELLAMULTOCIDA','GORDONIASPECIES','ACTINOMYCESSPECIES','DERMABACTERHOMINIS','STREP.GRPDNOTENTEROCOCCI','MICROCOCCUSSPECIES','CULTUREPOSITIVEGRAMPOSITIVECOCCI','DIPHTHEROIDS-CORYNEBACTERIUMSPECIES','GRAMNEGATIVERODS-NONFERM,UNIDENTIFIED','ACIDFASTBACILLI','ANAEROBICGRAMPOSITIVERODS','ENTERICGRAMNEGATIVERODS','CULTUREPOSITIVEGRAMNEGATIVECOCCI','GRAMPOSITIVERODS','GRAMNEGATIVERODS','NONSPORE-FORMINGANAEROBICGRAMPOSITIVERODS','LACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS-UNIDENTIFIED','NONLACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS','ACIDFASTBACILLIDETECTEDINLIQUIDMEDIUM','PARABACTEROIDESSPECIES','LISTERIASPECIES','LISTERIAMONOCYTOGENES','STREPTOCOCCUSSPECIES', 'KLEBSIELLASPECIES', 'PROTEUSSPECIES', 'ARCANOBACTERIUMHAEMOLYTICUM ', 'CRONOBACTERSAKAZAKII', 'CHRYSEOMONASLUTEOLA', 'LEUCONOSTOCSPECIES', 'BETASTREPTOCOCCUSGROUPG', 'PREVOTELLASPECIES', 'PEDIOCOCCUSSP.','ABIOTROPHIASPECIES(ORGRANULICATELLASPECIES)', 'CAMPYLOBACTERSPECIES', 'HAFNIA','RAHNELLA', 'ANAEROBICGRAMNEGATIVERODS', 'SHEWANELLAPUTREFACIENS', 'SCHISTOSOMAHAEMATOBIUMOVA', 'MYCOBACTERIUMSPECIES',' LECLERCIAADECARBOXYLATA', 'EGGERTHELLALENTA', 'YERSINIAENTEROCOLITICA','LACTOCOCCUSSPECIES', 'FLAVOBACTERIUMSPECIES', 'BREVUNDIMONAS', 'PEPTOSTREPTOCOCCUSSPECIES', 'BREVIBACTERIUMSPECIES', 'ZZZBACTEROIDESNOTB.FRAGILISGRP', 'VEILLONELLASPECIES', 'SHIGELLASPECIES', 'EUBACTERIUMLENTUM', 'COMAMONASACIDOVORANS', 'EWINGELLAAMERICANA', 'OLIGELLAURETHRALIS', 'ZZZPROPIONIBACTERIUMACNES', 'HAEMOPHILUSACTINOMYCETEMCOMITANS', 'MICROBACTERIUMSPECIES'],np.nan)
data = data.dropna()

data['organism'] = data['organism'].replace([r'\(CARBAPENEMRESISTANT\)','-VANCORESISTANT'],'',regex=True)

multiSwapss = {'ENTEROBACTERIACEAE':['MORGANELLAMORGANII','ESCHERICHIA_NOT_COLI','SAMONELLA_SPECIES','HAFNIAALVEI','KLUYVERA_SPECIES'],
               'BURKHOLDERIACEPACIA':['SPHINGO_SPECIES','ACHROMOBACTER_SPECIES','BURKHOLDERIACEPACIA_SPECIES'],
               'STREPTOCOCCUS_NOT_VIRIDANS':['STREPTOCOCCUS_GROUPA','STREPTOCOCCUS_GROUPC','STREPTOCOCCUS_GROUPD'],
               'ENTEROCOCCUS':['ENTEROCOCCUS._GALLINARUM','ENTEROCOCCUS_RARE_SPECIES'],
               'PROTEUS':['PROTEUS_NOT_MIRABILIS','PROTEUSMIRABILIS']}
               #'CHRYSEOBACTERIUMsss]s_FAMILY':['CHRYSEOBACTERIUM_SPECIES','ELIZABETHKINGIA_SPECIES'],
              # 'STREPTOCOCCUS_NOT_GROUPB_/VIRIDANS':['STREPTOCOCCUS_GROUPA','STREPTOCOCCUS_GROUPC','STREPTOCOCCUS_GROUPD'],
               #,
               #'FUSOBACTERIA/BACTEROIDESFRAGILIS':['FUSOBACTERIUM','BACTEROIDES_FRAGILIS_SPECIES'],
              # 'PROTEUS':['PROTEUS_NOT_MIRABILIS','PROTEUSMIRABILIS'],
               #'NOCARDIA/TSUKAMURELLA':['TSUKAMURELLA','NOCARDIA_SPECIES'],
              # 'BURKHOLDERIA/SPHINGO_SPECIES':['SPHINGO_SPECIES','ACHROMOBACTER_SPECIES','BURKHOLDERIACEPACIA_SPECIES']}

for replaceM in multiSwaps:
    data['organism'] = data['organism'].replace(multiSwaps[replaceM], replaceM)

for replaceM in multiSwapss:
    data['organism'] = data['organism'].replace(multiSwapss[replaceM], replaceM)
data['organism']=data['organism'].replace(['MORAXELLA','AEROCOCCUS','LACTOBACILLUS','RHIZOBIUMRADIOBACTER'],np.nan)
data=data.dropna()

print(len(data['organism'].unique()))
print(data.shape)
for organism,count in data['organism'].value_counts().items():
    print("organism: "+organism+ " "+str(count) )




#ordAntibiotic = OrdinalEncoder()
ordOrganism = OrdinalEncoder()

ordCultureDescription = OrdinalEncoder(categories=[['URINE','BLOOD','RESPIRATORY']])
ordTranslateAge = OrdinalEncoder(categories = [['18-24 years','25-34 years','35-44 years','45-54 years','55-64 years','65-74 years','75-84 years','85-89 years','above 90' ]])

tAge = ordTranslateAge.fit_transform(data[['age']])
tCulture = ordCultureDescription.fit_transform(data[['culture_description']])
tOrganism = ordOrganism.fit_transform(data[['organism']])
#tAntibiotic = ordAntibiotic.fit_transform(data[['antibiotic']])

ageDf = pd.DataFrame(tAge,columns=['age'],index=data.index)
cultureDf = pd.DataFrame(tCulture,columns=['culture_description'],index=data.index)
organismDf = pd.DataFrame(tOrganism,columns=['organism'],index=data.index)
#antibioticDf = pd.DataFrame(tAntibiotic,columns=['antibiotic'])

#fdss = pd.concat([data.drop(columns=['was_positive','age','culture_description','organism','antibiotic','anon_id','pat_enc_csn_id_coded' ,'order_proc_id_coded','charlsonCondition_anymalignancy/lymphoma/leukemia','charlsonCondition_cerebrovascularDisease','charlsonCondition_chronicPulmonaryDisease','charlsonCondition_congestiveHeartFailure','charlsonCondition_diabetesnoChronicComplication','charlsonCondition_diabeteswEndOrganDamage','charlsonCondition_hematologicDisease','charlsonCondition_metastaticSolidTumour','charlsonCondition_mildLiverDisease','charlsonCondition_moderateoSevereLiverDisease','charlsonCondition_myocardialInfraction','charlsonCondition_peripheralVascularDisease','charlsonCondition_renalDisease','charlsonCondition_rheumaticDisease']),ageDf,cultureDf,organismDf],axis=1)
fdss = pd.concat([data.drop(columns=['was_positive','age','culture_description','organism']),ageDf,cultureDf,organismDf],axis=1)
#swapsVancoResistant = {'KLEBSIELLAPNEUMONIAE(CARBAPENEMRESISTANT)':'KLEBSIELLAPNEUMONIAE',['ENTEROBACTERCLOACAECOMPLEX','ENTEROBACTERCLOACAECOMPLEX(CARBAPENEMRESISTANT)']:'ENTEROBACTERCLOACAE','ENTEROCOCCUSFAECALIS-VANCORESISTANT':'ENTEROCOCCUSFAECALIS','STREPTOCOCCUSAGALACTIAE{GROUPB}':'STREPTOCOCCUSAGALACTIAE(GROUPB)','SERRATIAMARCESCENS(CARBAPENEMRESISTANT)':'SERRATIAMARCESCENS','KLEBSIELLAAEROGENES(CARBAPENEMRESISTANT)':'KLEBSIELLAAEROGENES','ENTEROBACTERCLOACAECOMPLEX(CARBAPENEMRESISTANT)':'ENTEROBACTERCLOACAECOMPLEX','CITROBACTERKOSERI(CARBAPENEMRESISTANT)':'CITROBACTERKOSERI','ENTEROCOCCUSFAECIUM-VANCORESISTANT':'ENTEROCOCCUSFAECIUM',['ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP']:'PROTEUSVULGARIS'}


yTarget = fdss['organism']
fdss = fdss.drop('organism',axis=1)
print('data encoded')


xTrain,xTest,yTrain,yTest = train_test_split(fdss,yTarget,random_state=42)

trainingGrouped = pd.concat([xTrain,yTrain],axis=1)
print(fdss.shape)
print('oversampling started')
oversampledGroups = pd.DataFrame()

'''
randomSample = RandomOverSampler(sampling_strategy={1:250},random_state=42)
smotee = SMOTE(sampling_strategy={1:300,26:324},random_state=42)
bacteria = trainingGrouped[trainingGrouped['organism'].isin([1,26])]
print(bacteria.columns)
yr = bacteria['organism']
xr = bacteria.drop('organism',axis=1)
xrd,yrd = randomSample.fit_resample(xr,yr)

xsmoted,ysmoted = smotee.fit_resample(xrd,yrd)
sampledToAdd = pd.concat([xsmoted,ysmoted],axis=1)
oversampledGroups = pd.concat([oversampledGroups,sampledToAdd],ignore_index=True)
print('oversampling finished')

targetOversampled = oversampledGroups['organism']
dataOversampled = oversampledGroups.drop('organism',axis=1)
xTrain = pd.concat([xTrain,dataOversampled],ignore_index=True)
yTrain = pd.concat([yTrain,targetOversampled],ignore_index=True)
'''
print(xTrain.shape)
print(yTrain.shape)

#xTrain = xTrain.to_numpy().astype(np.float32)
print(xTrain.shape)
classWeights = {}
classCatWeights = []
for i, name in enumerate(ordOrganism.categories_[0]):
    print(i,name)
    classWeights[i]=1
    classCatWeights.append(1)

classWeights[2]=2
classWeights[3]=2


classWeights[5]=2


classWeights[7]=2
classWeights[12]=2


classWeights[20]=2.5


classWeights[21]=2



xTest = xTest.to_numpy().astype(np.float32).reshape(xTest.shape[0],-1)
print(xTest.shape)
print('train/test split set')

#antibioticAI = RandomForestClassifier(n_estimators=60,random_state=42)
# ('exT',ExtraTreesClassifier(class_weight=classWeights,n_estimators=60,random_state=42)),
estimators = [('randomF',RandomForestClassifier(class_weight=classWeights,max_features='log2',n_estimators=60,criterion='entropy',random_state=42)),
              ('exT',ExtraTreesClassifier(class_weight=classWeights,max_features='log2',criterion='entropy',n_estimators=60,random_state=42))
              ]
antibioticAI = joblib.load('antibioticAIstage1.joblib')

#final_estimator=(CatBoostClassifier(iterations=300,loss_function='MultiClassOneVsAll',eval_metric='TotalF1:average=Macro',learning_rate=0.02)
#antibioticAI = StackingClassifier(
   # estimators=estimators,final_estimator=(XGBClassifier(reg_lambda = 8,n_estimators = 120,learning_rate=0.1, objective = 'multi:softmax')),passthrough=True)


#antibioticAI.fit(xTrain,yTrain)
yPred = antibioticAI.predict(xTest)

#antibioticAI = RandomForestClassifier(n_estimators=60,random_state=42)

print('model created')
'''
for model in models:
paramsGrid = {'max_features':['auto','log2','sqrt'],
              'criterion':['gini','entropy']}
chooser = GridSearchCV(estimator=rf,param_grid=paramsGrid,scoring='f1_macro',cv=3)
notgunnaUSe,sampledX,notGunnause,sampledY = train_test_split(xTrain,yTrain,test_size=0.6,random_state=42,stratify=yTrain)
chooser.fit(sampledX,sampledY)
print('model trained')
print('best hyperparameters: '+chooser.best_params_)

antibioticAI = chooser.best_estimator_
'''

#antibioticAI = HistGradientBoostingClassifier(random_state=42)



print(classification_report(yTest,yPred, target_names=ordOrganism.categories_[0]))
#joblib.dump(antibioticAI,filename='antibioticAIstage1.joblib')
cm = confusion_matrix(yTest, yPred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=ordOrganism.categories_[0])
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

#print("Y test shape: "+str(yTest.shape))
#print("Y pred shape: "+ str(yPred.shape))

'''
#joblib.dump(antibioticAI,filename='antibioticAIstage1.joblib')
antibioticAI.fit(xTrain,yTrain)#joblib.dump(antibioticAI,filename='antibioticAIstage1.joblib')
print('model trained')
yPred = antibioticAI.predict(xTest)
print(classification_report(yTest,yPred, target_names=ordOrganism.categories_[0]))
#cm = confusion_matrix(yTest,yPred, labels=ordOrganism.categories_[0])
#cmPercents = cm.astype('float')/cm.sum(axis=1)[:,np.newaxis]

#pdCmPercents = pd.DataFrame(cmPercents,index=labels,columns=labels)
#print(pdCmPercents)
fNames = fdss.columns.values
importance = antibioticAI.feature_importances_
#importance = permutation_importance(antibioticAI,xTest,yTest,n_repeats =5,random_state=42)
print('permutation importance saved')
#importanceReady= importance.importances_mean.tolist()
fImportanceDF = pd.DataFrame({'Feature':fNames,'Gini Importance':importance}).sort_values('Gini Importance',ascending=False)
#uf wnat load the model later then: loadedAntibicAI = joblib.load('antibioticAIstage2.joblib')

fImportanceDF.to_csv("Stage1AIfeatureImportanceCheck.csv")

print(fImportanceDF)
plt.figure(figsize=(8,4))
plt.barh(fImportanceDF['Feature'], fImportanceDF['Gini Importance'],color="blue")
plt.xlabel('Gini Importance')
plt.title('Feature Importance - Gini Importance')
plt.gca().invert_yaxis()
plt.show()
'''

