print("started running")

#import torch.optim as optim
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#classification_report, classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

#for prepping data set as it uses words for descriptions
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
import io
import joblib

from sklearn.preprocessing import StandardScaler
import torch.optim.lr_scheduler as lr_scheduler

from io import StringIO
from sklearn.ensemble import RandomForestClassifier
#from sklearn.metrics import accuracy_score
import os
import re
from sklearn.metrics import classification_report
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.inspection import permutation_importance
from imblearn.over_sampling import SMOTE
pAth = os.path.dirname(os.path.abspath(__file__))

data=pd.read_csv(os.path.join(pAth,'stage2antibioticAI.csv'))
print(len(data['organism'].unique()))
print(data.shape)

multiSwaps = {'CORYNEBACTERIUM_PATHOGENCY_MODERATE':['CORYNEBACTERIUMSTRIATUM', 'CORYNEBACTERIUMMACGINLEYI', 'CORYNEBACTERIUMJEIKEIUM', 'CORYNEBACTERIUMPSEUDODIPHTHERITICUM','CORYNEBACTERIUMUREALYTICUM'],
              'CORYNEBACTERIUM_PATHOGENCY_LOW':['CORYNEBACTERIUMPROPINQUUM', 'CORYNEBACTERIUMACCOLENS', 'CORYNEBACTERIUMAMYCOLATUM', 'DIPHTHEROIDS-CORYNEBACTERIUMSPECIES', 'CORYNEBAC.STRIATUM/AMYCOLATUM'],
              'KLEBSIELLA.PNEUMONIAE':['KLEBSIELLAOZAENAE', 'KLEBSIELLAPNEUMONIAESSP.OZAENAE', 'KLEBSIELLAAEROGENES', 'KLEBSIELLAOXYTOCA', 'KLEBSIELLAPNEUMONIAE', 'ZZZENTEROBACTERAEROGENES'],
              'ENTEROCOCCUS._GALLINARUM':['ENTEROCOCCUSGALLINARUM', 'ENTEROCOCCUSCASSELIFLAVUS'],
              'ENTEROCOCCUS_RARE_SPECIES':['ENTEROCOCCUSSPECIES', 'ENTEROCOCCUSAVIUM', 'ENTEROCOCCUSRAFFINOSUS', 'ENTEROCOCCUSDURANS/HIRAE', 'ENTEROCOCCUSDURANS'],
              'MYCOBACTERIUMAVIUM_COMPLEX(MAC)':['MYCOBACTERIUMAVIUMCOMPLEX','CHROMOGENICAFB,NOTM.TUBERCULOSIS'],
              'MYCOBACTERIUM_RAPID_GROWING(RGM)':['MYCOBACTERIUMIMMUNOGENUM','MYCOBACTERIUMNEOAURUM', 'ZZZMYCOBACTERIUMMUCOGENICUM', 'MYCOBACTERIUMABSCESSUSGROUP','MYCOBACTERIUMABSCESSUS', 'MYCOBACTERIUMFORTUITUM', 'MYCOBACTERIUMCHELONAE', 'MYCOBACTERIUMSPECIES-RAPIDGROWER','MYCOBACTERIUMFORTUITUMSPECIESGROUP'],
              'CITROBACTER_SPECIES':['CITROBACTERKOSERI','CITROBACTERSPECIES','CITROBACTERAMALONATICUS','ZZZCITROBACTERAMALONATICUS','CITROBACTERAMALONATICUSCOMPLEX','CITROBACTERFREUNDIICOMPLEX', 'CITROBACTERFREUNDII', 'CITROBACTERYOUNGAE', 'CITROBACTERBRAAKII'],
              'COAGNEGATIVE_STAPHYLOCOCCUS_SPECIES':['STAPHYLOCOCCUSLUGDUNENSIS', 'COAGNEGATIVESTAPHYLOCOCCUS', 'STAPHYLOCOCCUSEPIDERMIDIS', 'STAPHNEGNOTLUGDUNENSIS','STAPHYLOCOCCUSHAEMOLYTICUS','STAPHYLOCOCCUSSPECIES-COAGNEGATIVE,NOTSTAPHSAPROPHYTICUS'],
              'STAPHYLOCOCCUSAUREUS_SPECIES': ['STAPHAUREUS{MRSA}','STAPHAUREUS(COLONYVARIANT-SMALLCOLONYOROTHERMORPHOTYPE)','STAPHYLOCOCCUSAUREUS'],
              'PROVIDENCIA_SPECIES':['PROVIDENCIARETTGERI', 'PROVIDENCIASTUARTII', 'PROVIDENCIASPECIES'],
              'SAMONELLA_SPECIES':['SALMONELLATYPHI', 'SALMONELLASPECIES', 'SALMONELLAENTERICA'],
              'BACTEROIDES_FRAGILIS_SPECIES':['ZZZBACTEROIDESFRAGILISGROUP','BACTEROIDESFRAGILIS'],
              'BURKHOLDERIACEPACIA_SPECIES':['BURKHOLDERIACEPACIA', 'BURKHOLDERIACEPACIACOMPLEX', 'BURKHOLDERIACEPACIACOMPLEXGENOMOVARI', 'BURKHOLDERIACENOCEPACIA', 'BURKHOLDERIAVIETNAMIENSIS', 'BURKHOLDERIAGLADIOLI','BURKHOLDERIAMULTIVORANS'],
              'NOCARDIA_SPECIES':['NOCARDIAFARCINICA', 'NOCARDIANOVA', 'NOCARDIASPECIES', 'NOCARDIACYRIACIGEORGICA', 'NOCARDIATRANSVALENSISCOMPLEX', 'NOCARDIATRANSVALENSIS', 'NOCARDIAASTEROIDES', 'NORCARDIAWALLACEI','NOCARDIANOVACOMPLEX'],
              'ENTEROBACTER_SPECIES':['ENTEROBACTERTAYLORAE', 'ENTEROBACTERCANCEROGENUS', 'ENTEROBACTERASBURIAE', 'ENTEROBACTERSPECIES', 'ENTEROBACTERAMNIGENUS', 'ENTEROBACTERGERGOVIAE', 'ENTEROBACTERCLOACAE','ENTEROBACTERAMNIGENUS1'],
              'SERRATIA_SPECIES':['SERRATIAMARCESCENS', 'SERRATIARUBIDAEA', 'SERRATIALIQUEFACIENS', 'SERRATIAODORIFERA', 'SERRATIASPECIES', 'SERRATIAPLYMUTHICA'],
              'ACINETOBACTER_SPECIES':['ACINETOBACTERSPECIES', 'ACINETOBACTERBAUMANNIICOMPLEX', 'ACINETOBACTERBAUMANNII', 'ACINETOBACTERLWOFFI', 'ACINETOBACTERHAEMOLYTICUS'],
              'SPHINGOBACTERIUM_SPECIES':['SPHINGOBACTERIUMMULTIVORUM', 'SPHINGOBACTERIUMSPIRITIVORUM'],
              'RALSTONIA_SPECIES':['RALSTONIAMANNITOLILYTICA', 'RALSTONIASPECIES'],
              'AEROMONA_SPECIES':['AEROMONASCAVIAE', 'AEROMONASHYDROPHILAGROUP', 'ZZAEROMONASHYDROPHILACOMPLEX', 'AEROMONASVERONII', 'ZZAEROMONASCAVIAECOMPLEX', 'AEROMONASSPECIES','ZZAEROMONASVERONIICOMPLEX'],
              'CHRYSEOBACTERIUM_SPECIES':['CHRYSEOBACTERIUMINDOLOGENES', 'CHRYSEOBACTERIUMSPECIES'],
              'ACHROMOBACTER_SPECIES':['ACHROMOBACTERSPECIES', 'ACHROMOBACTERXYLOSOXIDANS'],
              'ELIZABETHKINGIA_SPECIES':['ELIZABETHKINGIASPECIES', 'ELIZABETHKINGIAMENINGOSEPTICA'],
              'SPHINGOMONAS_SPECIES':['SPHINGOMONASPAUCIMOBILIS/PARAPAUCIMOBILIS', 'SPHINGOMONAS'],
              'STREPTOCOCCUS_GROUPA':['STREP.GRPDNOTENTEROCOCCI','STREPTOCOCCUSPYOGENES(GROUPA)','STREPTOCOCCUSPYOGENES{GROUPA}', 'BETASTREPTOCOCCUSSPECIES'],
              'STREPTOCOCCUS_VIRIDANS/ALPHAHEMOLYTIC':['STREPTOCOCCUSORALIS','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC','STREPTOCOCCUSSPECIES-ALPHAHEMOLYTIC,NOTS.PNEUMO','STREPTOCOCCUSPNEUMONIAE','STREPTOCOCCUSSALIVARIUSGROUP','STREPTOCOCCUSSALIVARIUS','STREPTOCOCCUSMUTANS','STREPTOCOCCUSMUTANSGROUP','STREPTOCOCCUSGORDONII','STREPTOCOCCUSMITISGROUP','STREPTOCOCCUSCONSTELLATUS','STREPTOCOCCUSMITIS','STREPTOCOCCUSSANGUINIS','STREPTOCOCCUSSANGUIS','STREPTOCOCCUSANGINOSUSGROUP','STREPTOCOCCUSPARASANGUINIS','STREPTOCOCCUSINTERMEDIUS','VIRIDANSGROUPSTREPTOCOCCI', 'VIRIDANSGROUPSTREPTOCOCCINOTS.PNEUMONIAE', 'STREPTOCOCCUSANGINOSUS', 'STREPTOCOCCUSMITIS/STREPTOCOCCUSORALIS'],
              'STREPTOCOCCUS_GROUPB':['STREPTOCOCCUSAGALACTIAE(GROUPB)','STREPTOCOCCUSAGALACTIAE{GROUPB}'],
              'STREPTOCOCCUS_GROUPC':['BETASTREPTOCOCCUSGROUPC','STREPTOCOCCUSDYSGALACTIAE','STREPTOCOCCUSDYSGALACTIAESUBSP.EQUISIMILIS(GROUPC/GSTR]'],
              'STREPTOCOCCUS_GROUPD':['STREPTOCOCCUSGALLOLYTICUS,SUBSP.GALLOLYTICUS','STREPTOCOCCUSGALLOLYTICUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.PASTEURIANUS','STREPTOCOCCUSGALLOLYTICUS,SUBSP.PASTEURIANUS','ZZZSTREPTOCOCCUSGALLOLYTICUSSUBSP.GALLOLYTICUS','STREPTOCOCCUSBOVISGP','STREPTOCOCCUSBOVISGP', 'STREPTOCOCCUSBOVIS','STREPTOCOCCUSBOVISGP.'],
              'PSEUDOMONAS_SPECIES':['PSEUDOMONASFLUORESCENS','PSEUDOMONASFLUORESCENSGROUP','PSEUDOMONASPUTIDA','PSEUDOMONASPUTIDAGROUP','PSEUDOMONASSTUTZERI','PSEUDOMONASSTUTZERIGROUP','PSEUDOMONASMENDOCINA','PSEUDOMONASAERUGINOSA(NON-MUCOIDCF)','PSEUDOMONASAERUGINOSA','MUCOIDPSEUDOMONASAERUGINOSA'],
              'PSEUDOMONAS_NOT_AERUGINOSA':['NON-FERMENTINGGRAMNEGATIVERODS-NOTP.AERUGINOSA','PSEUDOMONASSPECIES-NOTP.AERUGINOSA','PSEUDOMONASORYZIHABITANS'],
              'CLOSTIDIUMN_SPECIES':['CLOSTRIDIUMCLOSTRIDIOFORME', 'CLOSTRIDIUMPARAPUTRIFICUM', 'ZZZCLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSPECIES', 'CLOSTRIDIUMSORDELLII', 'CLOSTRIDIUMTERTIUM', 'CLOSTRIDIUMRAMOSUM', 'CLOSTRIDIUMSPECIES,NOTPERFRINGENS', 'CLOSTRIDIUMINNOCUUM', 'CLOSTRIDIUMSEPTICUM', 'CLOSTRIDIUMPERFRINGENS'],
              'PROTEUS_NOT_MIRABILIS':['ZZZPROTEUSPENNERI','ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP'],
              'ENTEROBACTERIACEAE_SPECIES_RARE_URINE':['MORGANELLAMORGANII','KLUYVERACRYOCRESCENS', 'KLUYVERAASCORBATA', 'KLUYVERASPECIES','RAOULTELLA', 'RAOULTELLAORNITHINOLYTICA', 'RAOULTELLAPLANTICOLA','ENTEROBACTERTAYLORAE','ENTEROBACTERCANCEROGENUS','ENTEROBACTERASBURIAE','ENTEROBACTERSPECIES','ENTEROBACTERCLOACAECOMPLEX','ENTEROBACTER_SPECIES','ENTEROBACTERAMNIGENUS1','ENTEROBACTERCLOACAE','ENTEROBACTERGERGOVIAE'],
              'FUSOBACTERIUM':['FUSOBACTERIUMNECROPHORUM', 'FUSOBACTERIUMSPECIES', 'FUSOBACTERIUMNUCLEATUM'],
              'LACTOBACILLUS':['LACTOBACILLUSRHAMNOSUS', 'LACTOBACILLUSSPECIES', 'LACTOBACILLUSCASEI'],
              'AEROCOCCUS':['AEROCOCCUSURINAE', 'AEROCOCCUSSANGUINICOLA','AEROCOCCUSSPECIES'],
              'MORAXELLA':['MORAXELLAOSLOENSIS','MORAXELLANON-LIQUEFACIENS','MORAXELLASPECIES'],
              'ALCALIGENES':['ALCALIGENESSPECIES','ALCALIGENESFAECALIS'],
              'ESCHERICHIA_NOT_COLI':['ESCHERICHIAFERGUSONII', 'ESCHERICHIAVULNERIS','ESCHERICHIAHERMANII'],
              'TSUKAMURELLA':['TSUKAMURELLASPECIES', 'TSUKAMURELLAPULMONIS'],
              'BACTEROIDES_SPECIES_NOT_FRAGILIS':['BACTEROIDESUREOLYTICUS', 'BACTEROIDESCACCAE', 'BACTEROIDESOVATUS', 'BACTEROIDESUNIFORMIS', 'BACTEROIDESVULGATUS', 'BACTEROIDESTHETAIOTAOMICRON', 'PARABACTEROIDESDISTASONIS', 'ZZZBACTEROIDESDISTASONIS', 'BACTEROIDESVULGATUS'],
              'PANTOEA_SPECIES':['PANTOEASPECIES','PANTOEAAGGLOMERANS']}


data['organism'] = data['organism'].replace([r'\(CARBAPENEMRESISTANT\)','-VANCORESISTANT'],'',regex=True)

for replaceM in multiSwaps:
    data['organism'] = data['organism'].replace(multiSwaps[replaceM], replaceM)


data['organism']=data['organism'].replace(['STREPTOCOCCUS_GROUPC','BURKHOLDERIACEPACIA_SPECIES','AEROMONA_SPECIES','STREPTOCOCCUS_GROUPB','CORYNEBACTERIUM_PATHOGENCY_LOW','STENOTROPHOMONASMALTOPHILIA','STREPTOCOCCUS_GROUPD','ESCHERICHIA_NOT_COLI','SPHINGOMONAS_SPECIES','STREPTOCOCCUS_GROUPA','MORAXELLA','AEROCOCCUS','PSEUDOMONAS_NOT_AERUGINOSA','PSEUDOMONASSPECIES-FLUORESCENS/PUTIDAGROUP','OCHROBACTRUMANTHROPI', 'OCHROBACTRUM','MYROIDESSPECIES','BACILLUSSPECIES','STAPHYLOCOCCUSSPECIES-NOTSTAPH.AUREUS','ESCHERICHIASPECIES','CORYNEBACTERIUMSPECIES','ARCANOBACTERIUMHAEMOLYTICUM','PAENIBACILLUSSPECIES','BACTEROIDESSPECIES','LECLERCIAADECARBOXYLATA','STAPHYLOCOCCUSSPECIES,COAGPENDING','STAPHYLOCOCCUSSPECIES','CORYNEBACTERIUMDIPTHERIAE','CORYNEBACTERIUMSPECIES,NOTC.UREALYTICUM','BORDETELLABRONCHISEPTICA','PSEUDOMONASSPECIES','BACTEROIDESSPECIESNOTFRAGILIS','ANAEROBICGRAMPOSITIVECOCCI','PASTEURELLAMULTOCIDA','GORDONIASPECIES','ACTINOMYCESSPECIES','DERMABACTERHOMINIS','STREP.GRPDNOTENTEROCOCCI','MICROCOCCUSSPECIES','CULTUREPOSITIVEGRAMPOSITIVECOCCI','DIPHTHEROIDS-CORYNEBACTERIUMSPECIES','GRAMNEGATIVERODS-NONFERM,UNIDENTIFIED','ACIDFASTBACILLI','ANAEROBICGRAMPOSITIVERODS','ENTERICGRAMNEGATIVERODS','CULTUREPOSITIVEGRAMNEGATIVECOCCI','GRAMPOSITIVERODS','GRAMNEGATIVERODS','NONSPORE-FORMINGANAEROBICGRAMPOSITIVERODS','LACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS-UNIDENTIFIED','NONLACTOSEFERMENTINGGRAMNEGATIVERODS','NONFERMENTINGGRAMNEGATIVERODS','ACIDFASTBACILLIDETECTEDINLIQUIDMEDIUM','PARABACTEROIDESSPECIES','LISTERIASPECIES','LISTERIAMONOCYTOGENES','STREPTOCOCCUSSPECIES', 'KLEBSIELLASPECIES', 'PROTEUSSPECIES', 'ARCANOBACTERIUMHAEMOLYTICUM ', 'CRONOBACTERSAKAZAKII', 'CHRYSEOMONASLUTEOLA', 'LEUCONOSTOCSPECIES', 'BETASTREPTOCOCCUSGROUPG', 'PREVOTELLASPECIES', 'PEDIOCOCCUSSP.','ABIOTROPHIASPECIES(ORGRANULICATELLASPECIES)', 'CAMPYLOBACTERSPECIES', 'HAFNIA','RAHNELLA', 'ANAEROBICGRAMNEGATIVERODS', 'SHEWANELLAPUTREFACIENS', 'SCHISTOSOMAHAEMATOBIUMOVA', 'MYCOBACTERIUMSPECIES',' LECLERCIAADECARBOXYLATA', 'EGGERTHELLALENTA', 'YERSINIAENTEROCOLITICA','LACTOCOCCUSSPECIES', 'FLAVOBACTERIUMSPECIES', 'BREVUNDIMONAS', 'PEPTOSTREPTOCOCCUSSPECIES', 'BREVIBACTERIUMSPECIES', 'ZZZBACTEROIDESNOTB.FRAGILISGRP', 'VEILLONELLASPECIES', 'SHIGELLASPECIES', 'EUBACTERIUMLENTUM', 'COMAMONASACIDOVORANS', 'EWINGELLAAMERICANA', 'OLIGELLAURETHRALIS', 'ZZZPROPIONIBACTERIUMACNES', 'HAEMOPHILUSACTINOMYCETEMCOMITANS', 'MICROBACTERIUMSPECIES',],np.nan)
data = data.dropna()
print(len(data['organism'].unique()))
print(data.shape)
for organism,count in data['culture_description'].value_counts().items():
    print("organism: "+organism+ " "+str(count))

data = data[data['culture_description']=='URINE'].copy()
for organism,count in data['culture_description'].value_counts().items():
    print("organism: "+organism+ " "+str(count))

ordTranslateAge = OrdinalEncoder(categories = [['18-24 years','25-34 years','35-44 years','45-54 years','55-64 years','65-74 years','75-84 years','85-89 years','above 90' ]])
'''
weights = {}
for organismName in data['organism'].unique():
    weights[organismName]=1


weights['ACHROMOBACTER_SPECIES'] = 1.5
weights['SPHINGOMONAS_SPECIES'] = 1.5
weights['SPHINGOBACTERIUM_SPECIES'] = 1.5
weights['HAFNIAALVEI'] = 1.5

'''
#ordAntibiotic = OrdinalEncoder()
ordOrganism = OrdinalEncoder()

ordCultureDescription = OrdinalEncoder(categories=[['URINE','BLOOD','RESPIRATORY']])

tAge = ordTranslateAge.fit_transform(data[['age']])
tOrganism = ordOrganism.fit_transform(data[['organism']])
#tAntibiotic = ordAntibiotic.fit_transform(data[['antibiotic']])

ageDf = pd.DataFrame(tAge,columns=['age'],index=data.index)
organismDf = pd.DataFrame(tOrganism,columns=['organism'],index=data.index)
#antibioticDf = pd.DataFrame(tAntibiotic,columns=['antibiotic'])

#fdss = pd.concat([data.drop(columns=['was_positive','age','culture_description','organism','antibiotic','anon_id','pat_enc_csn_id_coded' ,'order_proc_id_coded','charlsonCondition_anymalignancy/lymphoma/leukemia','charlsonCondition_cerebrovascularDisease','charlsonCondition_chronicPulmonaryDisease','charlsonCondition_congestiveHeartFailure','charlsonCondition_diabetesnoChronicComplication','charlsonCondition_diabeteswEndOrganDamage','charlsonCondition_hematologicDisease','charlsonCondition_metastaticSolidTumour','charlsonCondition_mildLiverDisease','charlsonCondition_moderateoSevereLiverDisease','charlsonCondition_myocardialInfraction','charlsonCondition_peripheralVascularDisease','charlsonCondition_renalDisease','charlsonCondition_rheumaticDisease']),ageDf,cultureDf,organismDf],axis=1)
fdss = pd.concat([data.drop(columns=['was_positive','age','culture_description','organism','antibiotic','anon_id','pat_enc_csn_id_coded' ,'order_proc_id_coded']),ageDf,organismDf],axis=1)
#swapsVancoResistant = {'KLEBSIELLAPNEUMONIAE(CARBAPENEMRESISTANT)':'KLEBSIELLAPNEUMONIAE',['ENTEROBACTERCLOACAECOMPLEX','ENTEROBACTERCLOACAECOMPLEX(CARBAPENEMRESISTANT)']:'ENTEROBACTERCLOACAE','ENTEROCOCCUSFAECALIS-VANCORESISTANT':'ENTEROCOCCUSFAECALIS','STREPTOCOCCUSAGALACTIAE{GROUPB}':'STREPTOCOCCUSAGALACTIAE(GROUPB)','SERRATIAMARCESCENS(CARBAPENEMRESISTANT)':'SERRATIAMARCESCENS','KLEBSIELLAAEROGENES(CARBAPENEMRESISTANT)':'KLEBSIELLAAEROGENES','ENTEROBACTERCLOACAECOMPLEX(CARBAPENEMRESISTANT)':'ENTEROBACTERCLOACAECOMPLEX','CITROBACTERKOSERI(CARBAPENEMRESISTANT)':'CITROBACTERKOSERI','ENTEROCOCCUSFAECIUM-VANCORESISTANT':'ENTEROCOCCUSFAECIUM',['ZZZPROTEUSVULGARIS','PROTEUSVULGARISGROUP']:'PROTEUSVULGARIS'}

fdss = fdss.drop('susceptibility',axis=1)
yTarget = fdss['organism']
fdss = fdss.drop('organism',axis=1)
print('data encoded')
xTrain, xTest,yTrain,yTest=train_test_split(fdss,yTarget,test_size=0.2,random_state=42)
xTrain = xTrain.to_numpy().astype(np.float32)
classWeights = {}

for i, name in enumerate(ordOrganism.categories_[0]):
    print(i,name)
    classWeights[i]=1


classWeights[9]=2
classWeights[10]=2
classWeights[12]=2
classWeights[14]=2
classWeights[17]=2
classWeights[22]=2




print(xTrain.shape)





xTest = xTest.to_numpy().astype(np.float32).reshape(xTest.shape[0],-1)
print(xTest.shape)
print('train/test split set')

smote = SMOTE(sampling_strategy={17:350,9:205,2:200,22:170},random_state=42)
xtrainsmoted,ytrainsmoted = smote.fit_resample(xTrain,yTrain)

antibioticAI = RandomForestClassifier(n_estimators=60, random_state=42,class_weight = classWeights)
#antibioticAI = HistGradientBoostingClassifier(random_state=42)
print('model created')
antibioticAI.fit(xtrainsmoted,ytrainsmoted)
print('model trained')
joblib.dump(antibioticAI,filename='antibioticAIstage1.joblib')

#antibioticAI = joblib.load('antibioticAIstage1.joblib')
yPred = antibioticAI.predict(xTest)


print("prediction made")

print("Y test shape: "+str(yTest.shape))
print("Y pred shape: "+ str(yPred.shape))

#joblib.dump(antibioticAI,filename='antibioticAIstage1.joblib')
print(classification_report(yTest,yPred))

fNames = fdss.columns.values
importance = antibioticAI.feature_importances_
#importance = permutation_importance(antibioticAI,xTest,yTest,n_repeats =5,random_state=42)
print('permutation importance saved')
#importanceReady= importance.importances_mean.tolist()
fImportanceDF = pd.DataFrame({'Feature':fNames,'Gini Importance':importance}).sort_values('Gini Importance',ascending=False)
#uf wnat load the model later then: loadedAntibicAI = joblib.load('antibioticAIstage2.joblib')

fImportanceDF.to_csv("Stage1AIfeatureImportanceCheck.csv")

print(fImportanceDF)
plt.figure(figsize=(8,4))
plt.barh(fImportanceDF['Feature'], fImportanceDF['Gini Importance'],color="blue")
plt.xlabel('Gini Importance')
plt.title('Feature Importance - Gini Importance')
plt.gca().invert_yaxis()
plt.show()


